/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1SplatRouteImport } from './routes/v1/$'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as LangOnboardingRouteImport } from './routes/$lang/onboarding'
import { Route as LangrootRouteRouteImport } from './routes/$lang/(root)/route'
import { Route as LangchatRouteRouteImport } from './routes/$lang/(chat)/route'
import { Route as LangauthRouteRouteImport } from './routes/$lang/(auth)/route'
import { Route as V1ContactsIndexRouteImport } from './routes/v1/contacts/index'
import { Route as LangrootIndexRouteImport } from './routes/$lang/(root)/index'
import { Route as V1RoomsMetadataRouteImport } from './routes/v1/rooms/metadata'
import { Route as LangchatMessagesRouteImport } from './routes/$lang/(chat)/messages'
import { Route as LangchatMeRouteImport } from './routes/$lang/(chat)/me'
import { Route as LangchatContactsRouteImport } from './routes/$lang/(chat)/contacts'
import { Route as LangauthWechatRouteImport } from './routes/$lang/(auth)/wechat'
import { Route as LangauthSignupRouteImport } from './routes/$lang/(auth)/signup'
import { Route as LangauthSigninRouteImport } from './routes/$lang/(auth)/signin'
import { Route as LangauthResetPasswordRouteImport } from './routes/$lang/(auth)/reset-password'
import { Route as LangauthForgotPasswordRouteImport } from './routes/$lang/(auth)/forgot-password'
import { Route as LangauthCellphoneRouteImport } from './routes/$lang/(auth)/cellphone'
import { Route as LangchatDiscoverRouteRouteImport } from './routes/$lang/(chat)/discover/route'
import { Route as LangchatDiscoverIndexRouteImport } from './routes/$lang/(chat)/discover/index'
import { Route as LangchatRoomsRoomIdRouteImport } from './routes/$lang/(chat)/rooms/$roomId'
import { Route as LangchatDiscoverSpacesSpaceIdRouteImport } from './routes/$lang/(chat)/discover/spaces/$spaceId'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SplatRoute = V1SplatRouteImport.update({
  id: '/v1/$',
  path: '/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangOnboardingRoute = LangOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => LangRoute,
} as any)
const LangrootRouteRoute = LangrootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => LangRoute,
} as any)
const LangchatRouteRoute = LangchatRouteRouteImport.update({
  id: '/(chat)',
  getParentRoute: () => LangRoute,
} as any)
const LangauthRouteRoute = LangauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => LangRoute,
} as any)
const V1ContactsIndexRoute = V1ContactsIndexRouteImport.update({
  id: '/v1/contacts/',
  path: '/v1/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangrootIndexRoute = LangrootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangrootRouteRoute,
} as any)
const V1RoomsMetadataRoute = V1RoomsMetadataRouteImport.update({
  id: '/v1/rooms/metadata',
  path: '/v1/rooms/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const LangchatMessagesRoute = LangchatMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => LangchatRouteRoute,
} as any)
const LangchatMeRoute = LangchatMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => LangchatRouteRoute,
} as any)
const LangchatContactsRoute = LangchatContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LangchatRouteRoute,
} as any)
const LangauthWechatRoute = LangauthWechatRouteImport.update({
  id: '/wechat',
  path: '/wechat',
  getParentRoute: () => LangauthRouteRoute,
} as any)
const LangauthSignupRoute = LangauthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LangauthRouteRoute,
} as any)
const LangauthSigninRoute = LangauthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => LangauthRouteRoute,
} as any)
const LangauthResetPasswordRoute = LangauthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => LangauthRouteRoute,
} as any)
const LangauthForgotPasswordRoute = LangauthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => LangauthRouteRoute,
} as any)
const LangauthCellphoneRoute = LangauthCellphoneRouteImport.update({
  id: '/cellphone',
  path: '/cellphone',
  getParentRoute: () => LangauthRouteRoute,
} as any)
const LangchatDiscoverRouteRoute = LangchatDiscoverRouteRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => LangchatRouteRoute,
} as any)
const LangchatDiscoverIndexRoute = LangchatDiscoverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangchatDiscoverRouteRoute,
} as any)
const LangchatRoomsRoomIdRoute = LangchatRoomsRoomIdRouteImport.update({
  id: '/rooms/$roomId',
  path: '/rooms/$roomId',
  getParentRoute: () => LangchatRouteRoute,
} as any)
const LangchatDiscoverSpacesSpaceIdRoute =
  LangchatDiscoverSpacesSpaceIdRouteImport.update({
    id: '/spaces/$spaceId',
    path: '/spaces/$spaceId',
    getParentRoute: () => LangchatDiscoverRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangrootRouteRouteWithChildren
  '/$lang/onboarding': typeof LangOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/v1/$': typeof V1SplatRoute
  '/$lang/discover': typeof LangchatDiscoverRouteRouteWithChildren
  '/$lang/cellphone': typeof LangauthCellphoneRoute
  '/$lang/forgot-password': typeof LangauthForgotPasswordRoute
  '/$lang/reset-password': typeof LangauthResetPasswordRoute
  '/$lang/signin': typeof LangauthSigninRoute
  '/$lang/signup': typeof LangauthSignupRoute
  '/$lang/wechat': typeof LangauthWechatRoute
  '/$lang/contacts': typeof LangchatContactsRoute
  '/$lang/me': typeof LangchatMeRoute
  '/$lang/messages': typeof LangchatMessagesRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/$lang/': typeof LangrootIndexRoute
  '/v1/contacts/': typeof V1ContactsIndexRoute
  '/$lang/rooms/$roomId': typeof LangchatRoomsRoomIdRoute
  '/$lang/discover/': typeof LangchatDiscoverIndexRoute
  '/$lang/discover/spaces/$spaceId': typeof LangchatDiscoverSpacesSpaceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangrootIndexRoute
  '/$lang/onboarding': typeof LangOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/v1/$': typeof V1SplatRoute
  '/$lang/cellphone': typeof LangauthCellphoneRoute
  '/$lang/forgot-password': typeof LangauthForgotPasswordRoute
  '/$lang/reset-password': typeof LangauthResetPasswordRoute
  '/$lang/signin': typeof LangauthSigninRoute
  '/$lang/signup': typeof LangauthSignupRoute
  '/$lang/wechat': typeof LangauthWechatRoute
  '/$lang/contacts': typeof LangchatContactsRoute
  '/$lang/me': typeof LangchatMeRoute
  '/$lang/messages': typeof LangchatMessagesRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/contacts': typeof V1ContactsIndexRoute
  '/$lang/rooms/$roomId': typeof LangchatRoomsRoomIdRoute
  '/$lang/discover': typeof LangchatDiscoverIndexRoute
  '/$lang/discover/spaces/$spaceId': typeof LangchatDiscoverSpacesSpaceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/(auth)': typeof LangauthRouteRouteWithChildren
  '/$lang/(chat)': typeof LangchatRouteRouteWithChildren
  '/$lang/(root)': typeof LangrootRouteRouteWithChildren
  '/$lang/onboarding': typeof LangOnboardingRoute
  '/api/$': typeof ApiSplatRoute
  '/v1/$': typeof V1SplatRoute
  '/$lang/(chat)/discover': typeof LangchatDiscoverRouteRouteWithChildren
  '/$lang/(auth)/cellphone': typeof LangauthCellphoneRoute
  '/$lang/(auth)/forgot-password': typeof LangauthForgotPasswordRoute
  '/$lang/(auth)/reset-password': typeof LangauthResetPasswordRoute
  '/$lang/(auth)/signin': typeof LangauthSigninRoute
  '/$lang/(auth)/signup': typeof LangauthSignupRoute
  '/$lang/(auth)/wechat': typeof LangauthWechatRoute
  '/$lang/(chat)/contacts': typeof LangchatContactsRoute
  '/$lang/(chat)/me': typeof LangchatMeRoute
  '/$lang/(chat)/messages': typeof LangchatMessagesRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/$lang/(root)/': typeof LangrootIndexRoute
  '/v1/contacts/': typeof V1ContactsIndexRoute
  '/$lang/(chat)/rooms/$roomId': typeof LangchatRoomsRoomIdRoute
  '/$lang/(chat)/discover/': typeof LangchatDiscoverIndexRoute
  '/$lang/(chat)/discover/spaces/$spaceId': typeof LangchatDiscoverSpacesSpaceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/onboarding'
    | '/api/$'
    | '/v1/$'
    | '/$lang/discover'
    | '/$lang/cellphone'
    | '/$lang/forgot-password'
    | '/$lang/reset-password'
    | '/$lang/signin'
    | '/$lang/signup'
    | '/$lang/wechat'
    | '/$lang/contacts'
    | '/$lang/me'
    | '/$lang/messages'
    | '/v1/rooms/metadata'
    | '/$lang/'
    | '/v1/contacts/'
    | '/$lang/rooms/$roomId'
    | '/$lang/discover/'
    | '/$lang/discover/spaces/$spaceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/$lang/onboarding'
    | '/api/$'
    | '/v1/$'
    | '/$lang/cellphone'
    | '/$lang/forgot-password'
    | '/$lang/reset-password'
    | '/$lang/signin'
    | '/$lang/signup'
    | '/$lang/wechat'
    | '/$lang/contacts'
    | '/$lang/me'
    | '/$lang/messages'
    | '/v1/rooms/metadata'
    | '/v1/contacts'
    | '/$lang/rooms/$roomId'
    | '/$lang/discover'
    | '/$lang/discover/spaces/$spaceId'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/(auth)'
    | '/$lang/(chat)'
    | '/$lang/(root)'
    | '/$lang/onboarding'
    | '/api/$'
    | '/v1/$'
    | '/$lang/(chat)/discover'
    | '/$lang/(auth)/cellphone'
    | '/$lang/(auth)/forgot-password'
    | '/$lang/(auth)/reset-password'
    | '/$lang/(auth)/signin'
    | '/$lang/(auth)/signup'
    | '/$lang/(auth)/wechat'
    | '/$lang/(chat)/contacts'
    | '/$lang/(chat)/me'
    | '/$lang/(chat)/messages'
    | '/v1/rooms/metadata'
    | '/$lang/(root)/'
    | '/v1/contacts/'
    | '/$lang/(chat)/rooms/$roomId'
    | '/$lang/(chat)/discover/'
    | '/$lang/(chat)/discover/spaces/$spaceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  V1SplatRoute: typeof V1SplatRoute
  V1RoomsMetadataRoute: typeof V1RoomsMetadataRoute
  V1ContactsIndexRoute: typeof V1ContactsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/$': {
      id: '/v1/$'
      path: '/v1/$'
      fullPath: '/v1/$'
      preLoaderRoute: typeof V1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/onboarding': {
      id: '/$lang/onboarding'
      path: '/onboarding'
      fullPath: '/$lang/onboarding'
      preLoaderRoute: typeof LangOnboardingRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/(root)': {
      id: '/$lang/(root)'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangrootRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/(chat)': {
      id: '/$lang/(chat)'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangchatRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/(auth)': {
      id: '/$lang/(auth)'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangauthRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/v1/contacts/': {
      id: '/v1/contacts/'
      path: '/v1/contacts'
      fullPath: '/v1/contacts/'
      preLoaderRoute: typeof V1ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/(root)/': {
      id: '/$lang/(root)/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangrootIndexRouteImport
      parentRoute: typeof LangrootRouteRoute
    }
    '/v1/rooms/metadata': {
      id: '/v1/rooms/metadata'
      path: '/v1/rooms/metadata'
      fullPath: '/v1/rooms/metadata'
      preLoaderRoute: typeof V1RoomsMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/(chat)/messages': {
      id: '/$lang/(chat)/messages'
      path: '/messages'
      fullPath: '/$lang/messages'
      preLoaderRoute: typeof LangchatMessagesRouteImport
      parentRoute: typeof LangchatRouteRoute
    }
    '/$lang/(chat)/me': {
      id: '/$lang/(chat)/me'
      path: '/me'
      fullPath: '/$lang/me'
      preLoaderRoute: typeof LangchatMeRouteImport
      parentRoute: typeof LangchatRouteRoute
    }
    '/$lang/(chat)/contacts': {
      id: '/$lang/(chat)/contacts'
      path: '/contacts'
      fullPath: '/$lang/contacts'
      preLoaderRoute: typeof LangchatContactsRouteImport
      parentRoute: typeof LangchatRouteRoute
    }
    '/$lang/(auth)/wechat': {
      id: '/$lang/(auth)/wechat'
      path: '/wechat'
      fullPath: '/$lang/wechat'
      preLoaderRoute: typeof LangauthWechatRouteImport
      parentRoute: typeof LangauthRouteRoute
    }
    '/$lang/(auth)/signup': {
      id: '/$lang/(auth)/signup'
      path: '/signup'
      fullPath: '/$lang/signup'
      preLoaderRoute: typeof LangauthSignupRouteImport
      parentRoute: typeof LangauthRouteRoute
    }
    '/$lang/(auth)/signin': {
      id: '/$lang/(auth)/signin'
      path: '/signin'
      fullPath: '/$lang/signin'
      preLoaderRoute: typeof LangauthSigninRouteImport
      parentRoute: typeof LangauthRouteRoute
    }
    '/$lang/(auth)/reset-password': {
      id: '/$lang/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/$lang/reset-password'
      preLoaderRoute: typeof LangauthResetPasswordRouteImport
      parentRoute: typeof LangauthRouteRoute
    }
    '/$lang/(auth)/forgot-password': {
      id: '/$lang/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/$lang/forgot-password'
      preLoaderRoute: typeof LangauthForgotPasswordRouteImport
      parentRoute: typeof LangauthRouteRoute
    }
    '/$lang/(auth)/cellphone': {
      id: '/$lang/(auth)/cellphone'
      path: '/cellphone'
      fullPath: '/$lang/cellphone'
      preLoaderRoute: typeof LangauthCellphoneRouteImport
      parentRoute: typeof LangauthRouteRoute
    }
    '/$lang/(chat)/discover': {
      id: '/$lang/(chat)/discover'
      path: '/discover'
      fullPath: '/$lang/discover'
      preLoaderRoute: typeof LangchatDiscoverRouteRouteImport
      parentRoute: typeof LangchatRouteRoute
    }
    '/$lang/(chat)/discover/': {
      id: '/$lang/(chat)/discover/'
      path: '/'
      fullPath: '/$lang/discover/'
      preLoaderRoute: typeof LangchatDiscoverIndexRouteImport
      parentRoute: typeof LangchatDiscoverRouteRoute
    }
    '/$lang/(chat)/rooms/$roomId': {
      id: '/$lang/(chat)/rooms/$roomId'
      path: '/rooms/$roomId'
      fullPath: '/$lang/rooms/$roomId'
      preLoaderRoute: typeof LangchatRoomsRoomIdRouteImport
      parentRoute: typeof LangchatRouteRoute
    }
    '/$lang/(chat)/discover/spaces/$spaceId': {
      id: '/$lang/(chat)/discover/spaces/$spaceId'
      path: '/spaces/$spaceId'
      fullPath: '/$lang/discover/spaces/$spaceId'
      preLoaderRoute: typeof LangchatDiscoverSpacesSpaceIdRouteImport
      parentRoute: typeof LangchatDiscoverRouteRoute
    }
  }
}

interface LangauthRouteRouteChildren {
  LangauthCellphoneRoute: typeof LangauthCellphoneRoute
  LangauthForgotPasswordRoute: typeof LangauthForgotPasswordRoute
  LangauthResetPasswordRoute: typeof LangauthResetPasswordRoute
  LangauthSigninRoute: typeof LangauthSigninRoute
  LangauthSignupRoute: typeof LangauthSignupRoute
  LangauthWechatRoute: typeof LangauthWechatRoute
}

const LangauthRouteRouteChildren: LangauthRouteRouteChildren = {
  LangauthCellphoneRoute: LangauthCellphoneRoute,
  LangauthForgotPasswordRoute: LangauthForgotPasswordRoute,
  LangauthResetPasswordRoute: LangauthResetPasswordRoute,
  LangauthSigninRoute: LangauthSigninRoute,
  LangauthSignupRoute: LangauthSignupRoute,
  LangauthWechatRoute: LangauthWechatRoute,
}

const LangauthRouteRouteWithChildren = LangauthRouteRoute._addFileChildren(
  LangauthRouteRouteChildren,
)

interface LangchatDiscoverRouteRouteChildren {
  LangchatDiscoverIndexRoute: typeof LangchatDiscoverIndexRoute
  LangchatDiscoverSpacesSpaceIdRoute: typeof LangchatDiscoverSpacesSpaceIdRoute
}

const LangchatDiscoverRouteRouteChildren: LangchatDiscoverRouteRouteChildren = {
  LangchatDiscoverIndexRoute: LangchatDiscoverIndexRoute,
  LangchatDiscoverSpacesSpaceIdRoute: LangchatDiscoverSpacesSpaceIdRoute,
}

const LangchatDiscoverRouteRouteWithChildren =
  LangchatDiscoverRouteRoute._addFileChildren(
    LangchatDiscoverRouteRouteChildren,
  )

interface LangchatRouteRouteChildren {
  LangchatDiscoverRouteRoute: typeof LangchatDiscoverRouteRouteWithChildren
  LangchatContactsRoute: typeof LangchatContactsRoute
  LangchatMeRoute: typeof LangchatMeRoute
  LangchatMessagesRoute: typeof LangchatMessagesRoute
  LangchatRoomsRoomIdRoute: typeof LangchatRoomsRoomIdRoute
}

const LangchatRouteRouteChildren: LangchatRouteRouteChildren = {
  LangchatDiscoverRouteRoute: LangchatDiscoverRouteRouteWithChildren,
  LangchatContactsRoute: LangchatContactsRoute,
  LangchatMeRoute: LangchatMeRoute,
  LangchatMessagesRoute: LangchatMessagesRoute,
  LangchatRoomsRoomIdRoute: LangchatRoomsRoomIdRoute,
}

const LangchatRouteRouteWithChildren = LangchatRouteRoute._addFileChildren(
  LangchatRouteRouteChildren,
)

interface LangrootRouteRouteChildren {
  LangrootIndexRoute: typeof LangrootIndexRoute
}

const LangrootRouteRouteChildren: LangrootRouteRouteChildren = {
  LangrootIndexRoute: LangrootIndexRoute,
}

const LangrootRouteRouteWithChildren = LangrootRouteRoute._addFileChildren(
  LangrootRouteRouteChildren,
)

interface LangRouteChildren {
  LangauthRouteRoute: typeof LangauthRouteRouteWithChildren
  LangchatRouteRoute: typeof LangchatRouteRouteWithChildren
  LangrootRouteRoute: typeof LangrootRouteRouteWithChildren
  LangOnboardingRoute: typeof LangOnboardingRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangauthRouteRoute: LangauthRouteRouteWithChildren,
  LangchatRouteRoute: LangchatRouteRouteWithChildren,
  LangrootRouteRoute: LangrootRouteRouteWithChildren,
  LangOnboardingRoute: LangOnboardingRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  V1SplatRoute: V1SplatRoute,
  V1RoomsMetadataRoute: V1RoomsMetadataRoute,
  V1ContactsIndexRoute: V1ContactsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
