import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState, useRef, useCallback, lazy, Suspense } from 'react'
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@libs/react-shared/ui/card'
import { Button } from '@libs/react-shared/ui/button'
import { Input } from '@libs/react-shared/ui/input'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@libs/react-shared/ui/select'
import { Label } from '@libs/react-shared/ui/label'
import {
  FileUpload,
  FileUploadDropzone,
  FileUploadItem,
  FileUploadItemDelete,
  FileUploadItemMetadata,
  FileUploadItemPreview,
  FileUploadItemProgress,
  FileUploadList,
} from '@libs/react-shared/ui/file-upload'
import { SaveIcon, Trash2Icon, Upload, X } from 'lucide-react'
import { useForm, Controller } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@libs/react-shared/ui/alert-dialog'
import { toast } from 'sonner'
import { Skeleton } from '@libs/react-shared/ui/skeleton'
import { useTranslation } from '@/hooks/use-translation'
import { useTheme } from '@libs/react-shared/hooks/use-theme'
import { createBlogPostValidators, createNextTranslationFunction } from '@libs/validators'
import '@uiw/react-md-editor/markdown-editor.css'
import '@uiw/react-markdown-preview/markdown.css'

const MDEditor = lazy(() => import('@uiw/react-md-editor'))

export const Route = createFileRoute('/$lang/admin/blog/$id/')({
  component: BlogPostPage,
})

function slugFromTitle(title: string): string {
  return title
    .toLowerCase()
    .replace(/\s+/g, '-')
    .replace(/[^a-z0-9-]/g, '')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '') || 'post'
}

async function uploadFile(file: File): Promise<string | null> {
  const formData = new FormData()
  formData.append('file', file)
  formData.append('provider', 'r2')
  try {
    const res = await fetch('/api/upload', { method: 'POST', body: formData })
    if (!res.ok) return null
    const data = await res.json()
    return data.data?.url || null
  } catch {
    return null
  }
}

function BlogPostPage() {
  const { t, locale } = useTranslation()
  const { theme } = useTheme()
  const tWithParams = createNextTranslationFunction(t)
  const { blogPostFormSchema } = createBlogPostValidators(tWithParams)
  type BlogFormData = z.infer<typeof blogPostFormSchema>

  const { id } = Route.useParams()
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [coverImage, setCoverImage] = useState<string>('')
  const [coverFiles, setCoverFiles] = useState<File[]>([])
  const slugAutoGeneratedRef = useRef(true)
  const [editorMounted, setEditorMounted] = useState(false)
  useEffect(() => { setEditorMounted(true) }, [])

  const isEditMode = id !== 'new'

  const {
    register,
    handleSubmit,
    control,
    reset,
    watch,
    setValue,
    formState: { errors },
  } = useForm<BlogFormData>({
    resolver: zodResolver(blogPostFormSchema),
    defaultValues: {
      title: '',
      slug: '',
      excerpt: '',
      coverImage: '',
      status: 'draft' as const,
      content: '',
    },
    mode: 'onBlur',
  })

  const title = watch('title')
  const slug = watch('slug')

  useEffect(() => {
    if (!title) return
    const newSlug = slugFromTitle(title)
    if (slugAutoGeneratedRef.current || !slug || slug.trim() === '') {
      setValue('slug', newSlug)
      slugAutoGeneratedRef.current = true
    }
  }, [title, setValue])

  const handleSlugChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    slugAutoGeneratedRef.current = false
    setValue('slug', e.target.value)
  }

  useEffect(() => {
    const fetchPost = async () => {
      if (id === 'new') {
        slugAutoGeneratedRef.current = true
        setLoading(false)
        return
      }

      try {
        const response = await fetch(`/api/admin/blog/${id}`)
        if (!response.ok) {
          throw new Error(t.admin.blog.messages.fetchError)
        }
        const post = await response.json()
        reset({
          title: post.title,
          slug: post.slug,
          excerpt: post.excerpt || '',
          coverImage: post.coverImage || '',
          status: post.status,
          content: post.content || '',
        })
        setCoverImage(post.coverImage || '')
        slugAutoGeneratedRef.current = false
        setLoading(false)
      } catch (err) {
        setError(err instanceof Error ? err.message : t.admin.blog.messages.fetchError)
        setLoading(false)
      }
    }

    fetchPost()
  }, [id, reset, t])

  const handleCoverUpload = useCallback(
    async (
      files: File[],
      { onSuccess, onError }: {
        onProgress: (file: File, progress: number) => void
        onSuccess: (file: File) => void
        onError: (file: File, error: Error) => void
      },
    ) => {
      const file = files[0]
      if (!file) return
      const url = await uploadFile(file)
      if (url) {
        setCoverImage(url)
        setValue('coverImage', url)
        toast.success(t.admin.blog.messages.uploadSuccess)
        onSuccess(file)
      } else {
        toast.error(t.admin.blog.messages.uploadError)
        onError(file, new Error('Upload failed'))
      }
    },
    [setValue, t],
  )

  const removeCoverImage = () => {
    setCoverImage('')
    setCoverFiles([])
    setValue('coverImage', '')
  }

  const handleEditorPaste = useCallback(
    async (e: React.ClipboardEvent) => {
      const items = e.clipboardData?.items
      if (!items) return
      for (const item of Array.from(items)) {
        if (item.type.startsWith('image/')) {
          e.preventDefault()
          const file = item.getAsFile()
          if (!file) continue
          const url = await uploadFile(file)
          if (url) {
            const currentContent = watch('content') || ''
            setValue('content', currentContent + `\n![image](${url})\n`)
            toast.success(t.admin.blog.messages.uploadSuccess)
          } else {
            toast.error(t.admin.blog.messages.uploadError)
          }
          break
        }
      }
    },
    [watch, setValue, t],
  )

  const handleEditorDrop = useCallback(
    async (e: React.DragEvent) => {
      const files = e.dataTransfer?.files
      if (!files?.length) return
      for (const file of Array.from(files)) {
        if (file.type.startsWith('image/')) {
          e.preventDefault()
          const url = await uploadFile(file)
          if (url) {
            const currentContent = watch('content') || ''
            setValue('content', currentContent + `\n![image](${url})\n`)
            toast.success(t.admin.blog.messages.uploadSuccess)
          } else {
            toast.error(t.admin.blog.messages.uploadError)
          }
        }
      }
    },
    [watch, setValue, t],
  )

  const onSubmit = async (data: BlogFormData) => {
    setError(null)

    const payload = { ...data, coverImage }
    if (!payload.slug?.trim() && payload.title) {
      payload.slug = slugFromTitle(payload.title)
    }

    try {
      if (isEditMode && id) {
        const res = await fetch(`/api/admin/blog/${id}`, {
          method: 'PATCH',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        })
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}))
          throw new Error(errData.error || t.admin.blog.messages.operationFailed)
        }
        toast.success(t.admin.blog.messages.updateSuccess)
      } else {
        const res = await fetch('/api/admin/blog', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload),
        })
        if (!res.ok) {
          const errData = await res.json().catch(() => ({}))
          throw new Error(errData.error || t.admin.blog.messages.operationFailed)
        }
        toast.success(t.admin.blog.messages.createSuccess)
      }

      window.location.href = `/${locale}/admin/blog`
    } catch (err) {
      const msg = err instanceof Error ? err.message : t.admin.blog.messages.operationFailed
      setError(msg)
      toast.error(msg)
    }
  }

  const handleDelete = async () => {
    if (!id) return
    try {
      const res = await fetch(`/api/admin/blog/${id}`, { method: 'DELETE' })
      if (!res.ok) {
        throw new Error(t.admin.blog.messages.deleteError)
      }
      toast.success(t.admin.blog.messages.deleteSuccess)
      window.location.href = `/${locale}/admin/blog`
    } catch (err) {
      const msg = err instanceof Error ? err.message : t.admin.blog.messages.deleteError
      setError(msg)
      toast.error(msg)
    }
  }

  if (loading) {
    return (
      <div className="container mx-auto p-10">
        <div className="mb-6">
          <Skeleton className="h-6 w-32" />
        </div>
        <Skeleton className="h-10 w-60 mb-6" />
        <Card className="max-w-5xl mx-auto">
          <CardHeader>
            <Skeleton className="h-7 w-40 mb-2" />
            <Skeleton className="h-4 w-60" />
          </CardHeader>
          <CardContent className="space-y-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="space-y-2">
                <Skeleton className="h-5 w-24" />
                <Skeleton className="h-10 w-full" />
              </div>
            ))}
          </CardContent>
          <CardFooter className="pt-6">
            <Skeleton className="h-10 w-32" />
          </CardFooter>
        </Card>
      </div>
    )
  }

  return (
    <div className="container mx-auto p-10">
      <div className="flex items-center mb-6">
        <a href={`/${locale}/admin/blog`} className="text-blue-500 hover:text-blue-700">
          &larr; {t.actions.backToBlog}
        </a>
      </div>

      <h1 className="text-3xl font-bold mb-6">
        {isEditMode ? t.admin.blog.editPost : t.admin.blog.createPost}
      </h1>

      {error && (
        <div className="mb-4 p-4 text-red-700 bg-red-100 rounded-md">{error}</div>
      )}

      <form onSubmit={handleSubmit(onSubmit)} className="max-w-5xl mx-auto">
        <Card>
          <CardHeader>
            <CardTitle>{t.admin.blog.form.title}</CardTitle>
            <CardDescription>{t.admin.blog.form.description}</CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="title">{t.admin.blog.form.labels.title}</Label>
              <Input
                id="title"
                {...register('title')}
                placeholder={t.admin.blog.form.placeholders.title}
                className={errors.title ? 'border-red-500' : ''}
              />
              {errors.title && (
                <p className="text-red-500 text-sm">{errors.title.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="slug">{t.admin.blog.form.labels.slug}</Label>
              <Input
                id="slug"
                value={slug}
                onChange={handleSlugChange}
                placeholder={t.admin.blog.form.placeholders.slug}
                className={errors.slug ? 'border-red-500' : ''}
              />
              {errors.slug && (
                <p className="text-red-500 text-sm">{errors.slug.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="excerpt">{t.admin.blog.form.labels.excerpt}</Label>
              <textarea
                id="excerpt"
                {...register('excerpt')}
                placeholder={t.admin.blog.form.placeholders.excerpt}
                rows={3}
                className="flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              />
            </div>

            <div className="space-y-2">
              <Label>{t.admin.blog.form.labels.coverImage}</Label>
              {coverImage ? (
                <div className="relative mb-2">
                  <img
                    src={coverImage}
                    alt="Cover"
                    className="w-full h-48 object-cover rounded-md border"
                  />
                  <Button
                    type="button"
                    variant="destructive"
                    size="sm"
                    className="absolute top-2 right-2"
                    onClick={removeCoverImage}
                  >
                    <X className="h-4 w-4" />
                  </Button>
                </div>
              ) : (
                <FileUpload
                  value={coverFiles}
                  onValueChange={setCoverFiles}
                  accept="image/*"
                  maxFiles={1}
                  maxSize={2 * 1024 * 1024}
                  onUpload={handleCoverUpload}
                >
                  <FileUploadDropzone className="border-dashed p-6">
                    <div className="flex flex-col items-center gap-2 text-center">
                      <Upload className="h-8 w-8 text-muted-foreground" />
                      <p className="text-sm text-muted-foreground">
                        {t.admin.blog.form.placeholders.coverImage}
                      </p>
                    </div>
                  </FileUploadDropzone>
                  <FileUploadList>
                    {coverFiles.map((file, index) => (
                      <FileUploadItem key={index} value={file}>
                        <FileUploadItemPreview />
                        <FileUploadItemMetadata />
                        <FileUploadItemProgress />
                        <FileUploadItemDelete />
                      </FileUploadItem>
                    ))}
                  </FileUploadList>
                </FileUpload>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="status">{t.admin.blog.form.labels.status}</Label>
              <Controller
                name="status"
                control={control}
                render={({ field }) => (
                  <Select onValueChange={field.onChange} value={field.value}>
                    <SelectTrigger className={errors.status ? 'border-red-500' : ''}>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="draft">{t.admin.blog.table.search.draft}</SelectItem>
                      <SelectItem value="published">{t.admin.blog.table.search.published}</SelectItem>
                    </SelectContent>
                  </Select>
                )}
              />
              {errors.status && (
                <p className="text-red-500 text-sm">{errors.status.message}</p>
              )}
            </div>

            <div className="space-y-2">
              <Label htmlFor="content">{t.admin.blog.form.labels.content}</Label>
              <Controller
                name="content"
                control={control}
                render={({ field }) => (
                  <div
                    data-color-mode={theme === 'dark' ? 'dark' : 'light'}
                    className="[&_.w-md-editor]:min-h-[300px]"
                    onPaste={handleEditorPaste}
                    onDrop={handleEditorDrop}
                    onDragOver={(e) => e.preventDefault()}
                  >
                    {editorMounted ? (
                      <Suspense fallback={<div className="h-[400px] w-full rounded-md border border-input bg-background animate-pulse" />}>
                        <MDEditor
                          value={field.value || ''}
                          onChange={field.onChange}
                          preview="live"
                          height={400}
                          visibleDragbar={false}
                        />
                      </Suspense>
                    ) : (
                      <div className="h-[400px] w-full rounded-md border border-input bg-background" />
                    )}
                  </div>
                )}
              />
            </div>
          </CardContent>
          <CardFooter className="flex justify-between space-x-4 pt-6">
            <div className="flex space-x-4">
              <Button type="submit" className="flex items-center gap-2">
                <SaveIcon className="h-4 w-4" />
                {isEditMode ? t.actions.saveChanges : t.actions.createPost}
              </Button>

              {isEditMode && (
                <AlertDialog>
                  <AlertDialogTrigger asChild>
                    <Button
                      variant="destructive"
                      type="button"
                      className="flex items-center gap-2"
                    >
                      <Trash2Icon className="h-4 w-4" />
                      {t.actions.deletePost}
                    </Button>
                  </AlertDialogTrigger>
                  <AlertDialogContent>
                    <AlertDialogHeader>
                      <AlertDialogTitle>{t.admin.blog.deleteDialog.title}</AlertDialogTitle>
                      <AlertDialogDescription>
                        {t.admin.blog.deleteDialog.description}
                      </AlertDialogDescription>
                    </AlertDialogHeader>
                    <AlertDialogFooter>
                      <AlertDialogCancel>{t.actions.cancel}</AlertDialogCancel>
                      <AlertDialogAction
                        onClick={handleDelete}
                        className="bg-red-600 hover:bg-red-700"
                      >
                        {t.actions.delete}
                      </AlertDialogAction>
                    </AlertDialogFooter>
                  </AlertDialogContent>
                </AlertDialog>
              )}
            </div>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}
