/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangrootRouteRouteImport } from './routes/$lang/(root)/route'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as LangrootIndexRouteImport } from './routes/$lang/(root)/index'
import { Route as ApiBlogSlugRouteImport } from './routes/api/blog/$slug'
import { Route as LangrootBlogIndexRouteImport } from './routes/$lang/(root)/blog/index'
import { Route as LangrootBlogSlugRouteImport } from './routes/$lang/(root)/blog/$slug'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangrootRouteRoute = LangrootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => LangRoute,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangrootIndexRoute = LangrootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangrootRouteRoute,
} as any)
const ApiBlogSlugRoute = ApiBlogSlugRouteImport.update({
  id: '/api/blog/$slug',
  path: '/api/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangrootBlogIndexRoute = LangrootBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangrootRouteRoute,
} as any)
const LangrootBlogSlugRoute = LangrootBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangrootRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangrootRouteRouteWithChildren
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/$lang/': typeof LangrootIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/$lang/blog/$slug': typeof LangrootBlogSlugRoute
  '/$lang/blog/': typeof LangrootBlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang': typeof LangrootIndexRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/$lang/blog/$slug': typeof LangrootBlogSlugRoute
  '/$lang/blog': typeof LangrootBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/(root)': typeof LangrootRouteRouteWithChildren
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/$lang/(root)/': typeof LangrootIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/$lang/(root)/blog/$slug': typeof LangrootBlogSlugRoute
  '/$lang/(root)/blog/': typeof LangrootBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/api/blog/$slug'
    | '/$lang/'
    | '/api/blog/'
    | '/$lang/blog/$slug'
    | '/$lang/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang'
    | '/api/blog/$slug'
    | '/api/blog'
    | '/$lang/blog/$slug'
    | '/$lang/blog'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/(root)'
    | '/api/blog/$slug'
    | '/$lang/(root)/'
    | '/api/blog/'
    | '/$lang/(root)/blog/$slug'
    | '/$lang/(root)/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiBlogSlugRoute: typeof ApiBlogSlugRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/(root)': {
      id: '/$lang/(root)'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangrootRouteRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/(root)/': {
      id: '/$lang/(root)/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangrootIndexRouteImport
      parentRoute: typeof LangrootRouteRoute
    }
    '/api/blog/$slug': {
      id: '/api/blog/$slug'
      path: '/api/blog/$slug'
      fullPath: '/api/blog/$slug'
      preLoaderRoute: typeof ApiBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/(root)/blog/': {
      id: '/$lang/(root)/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangrootBlogIndexRouteImport
      parentRoute: typeof LangrootRouteRoute
    }
    '/$lang/(root)/blog/$slug': {
      id: '/$lang/(root)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangrootBlogSlugRouteImport
      parentRoute: typeof LangrootRouteRoute
    }
  }
}

interface LangrootRouteRouteChildren {
  LangrootIndexRoute: typeof LangrootIndexRoute
  LangrootBlogSlugRoute: typeof LangrootBlogSlugRoute
  LangrootBlogIndexRoute: typeof LangrootBlogIndexRoute
}

const LangrootRouteRouteChildren: LangrootRouteRouteChildren = {
  LangrootIndexRoute: LangrootIndexRoute,
  LangrootBlogSlugRoute: LangrootBlogSlugRoute,
  LangrootBlogIndexRoute: LangrootBlogIndexRoute,
}

const LangrootRouteRouteWithChildren = LangrootRouteRoute._addFileChildren(
  LangrootRouteRouteChildren,
)

interface LangRouteChildren {
  LangrootRouteRoute: typeof LangrootRouteRouteWithChildren
}

const LangRouteChildren: LangRouteChildren = {
  LangrootRouteRoute: LangrootRouteRouteWithChildren,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiBlogSlugRoute: ApiBlogSlugRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
