/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as rootRouteRouteImport } from './routes/(root)/route'
import { Route as rootIndexRouteImport } from './routes/(root)/index'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as rootBlogIndexRouteImport } from './routes/(root)/blog/index'
import { Route as ApiBlogSlugRouteImport } from './routes/api/blog/$slug'
import { Route as rootBlogSlugRouteImport } from './routes/(root)/blog/$slug'

const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const rootRouteRoute = rootRouteRouteImport.update({
  id: '/(root)',
  getParentRoute: () => rootRouteImport,
} as any)
const rootIndexRoute = rootIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const rootBlogIndexRoute = rootBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteRoute,
} as any)
const ApiBlogSlugRoute = ApiBlogSlugRouteImport.update({
  id: '/api/blog/$slug',
  path: '/api/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const rootBlogSlugRoute = rootBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/': typeof rootIndexRoute
  '/blog/$slug': typeof rootBlogSlugRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/blog/': typeof rootBlogIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
}
export interface FileRoutesByTo {
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/': typeof rootIndexRoute
  '/blog/$slug': typeof rootBlogSlugRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/blog': typeof rootBlogIndexRoute
  '/api/blog': typeof ApiBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(root)': typeof rootRouteRouteWithChildren
  '/$locale': typeof LocaleRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/(root)/': typeof rootIndexRoute
  '/(root)/blog/$slug': typeof rootBlogSlugRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/(root)/blog/': typeof rootBlogIndexRoute
  '/api/blog/': typeof ApiBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/$locale/$'
    | '/'
    | '/blog/$slug'
    | '/api/blog/$slug'
    | '/blog/'
    | '/api/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale'
    | '/$locale/$'
    | '/'
    | '/blog/$slug'
    | '/api/blog/$slug'
    | '/blog'
    | '/api/blog'
  id:
    | '__root__'
    | '/(root)'
    | '/$locale'
    | '/$locale/$'
    | '/(root)/'
    | '/(root)/blog/$slug'
    | '/api/blog/$slug'
    | '/(root)/blog/'
    | '/api/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  rootRouteRoute: typeof rootRouteRouteWithChildren
  LocaleRoute: typeof LocaleRouteWithChildren
  ApiBlogSlugRoute: typeof ApiBlogSlugRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)': {
      id: '/(root)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof rootRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/': {
      id: '/(root)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/blog/': {
      id: '/(root)/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof rootBlogIndexRouteImport
      parentRoute: typeof rootRouteRoute
    }
    '/api/blog/$slug': {
      id: '/api/blog/$slug'
      path: '/api/blog/$slug'
      fullPath: '/api/blog/$slug'
      preLoaderRoute: typeof ApiBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(root)/blog/$slug': {
      id: '/(root)/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof rootBlogSlugRouteImport
      parentRoute: typeof rootRouteRoute
    }
  }
}

interface rootRouteRouteChildren {
  rootIndexRoute: typeof rootIndexRoute
  rootBlogSlugRoute: typeof rootBlogSlugRoute
  rootBlogIndexRoute: typeof rootBlogIndexRoute
}

const rootRouteRouteChildren: rootRouteRouteChildren = {
  rootIndexRoute: rootIndexRoute,
  rootBlogSlugRoute: rootBlogSlugRoute,
  rootBlogIndexRoute: rootBlogIndexRoute,
}

const rootRouteRouteWithChildren = rootRouteRoute._addFileChildren(
  rootRouteRouteChildren,
)

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  rootRouteRoute: rootRouteRouteWithChildren,
  LocaleRoute: LocaleRouteWithChildren,
  ApiBlogSlugRoute: ApiBlogSlugRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
