// Generated by scripts/generate-official-catalog.mjs. Do not edit.
export const officialTemplateDefinitions = [
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-arcade",
      "slug": "arcade",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "play",
      "name": {
        "en": "Pixel Saturday",
        "zh-CN": "像素星期六"
      },
      "summary": {
        "en": "A handheld-console hangout where reactions become collectible pixel badges.",
        "zh-CN": "带一点掌机颗粒感的朋友 Space，互动会变成可以收集的像素徽章。"
      },
      "author": "8-Bit Picnic",
      "icon": "✦",
      "accent": "#ffd84d",
      "canvas": "#34274f",
      "currentVersionId": "tplv-space-arcade-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c",
          "manifestHash": "sha256:f31c6e092c2936f9de6de99b6161c7ae86737f58dc2b7aec220360a6ed03511e"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-cd8f14588018f1646aa6868075c5e58b13546c4581b5400dbcaeab2956c85019",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:cd8f14588018f1646aa6868075c5e58b13546c4581b5400dbcaeab2956c85019"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:cd8f14588018f1646aa6868075c5e58b13546c4581b5400dbcaeab2956c85019",
          "manifestHash": "sha256:99ee3fee6e2f573de8980795cfdd298ab788004bd1086cdc6722506eb8fe218c"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-ce92262abad8cea95133bd21e6daf5d20b8ac23d3db306b7833131059f20e627",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:ce92262abad8cea95133bd21e6daf5d20b8ac23d3db306b7833131059f20e627"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:ce92262abad8cea95133bd21e6daf5d20b8ac23d3db306b7833131059f20e627",
          "manifestHash": "sha256:04e9d65ed6151280c7c941c8118620f524fdc7b0cca83cf8dadb35d3f9655ef4"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-campfire",
      "slug": "campfire",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "daily",
      "name": {
        "en": "Afterglow Radio",
        "zh-CN": "夜航电台"
      },
      "summary": {
        "en": "A slow-moving late-night radio Space for the last thoughts of the day.",
        "zh-CN": "像深夜电台一样缓慢流动的 Space，适合分享一天最后的心事。"
      },
      "author": "Vibe Chat Studio",
      "icon": "◐",
      "accent": "#ff6b42",
      "canvas": "#171b20",
      "currentVersionId": "tplv-space-campfire-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a",
          "manifestHash": "sha256:942824609f34c91a55bce3261ecd80babbd3130dbb495fe083f3c26c466d13ad"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-971b7254741afab05e47616b36a86d0ff512d777e6f8c3cb38b78bb2b2dd506b",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:971b7254741afab05e47616b36a86d0ff512d777e6f8c3cb38b78bb2b2dd506b"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:971b7254741afab05e47616b36a86d0ff512d777e6f8c3cb38b78bb2b2dd506b",
          "manifestHash": "sha256:56c721d600ffdf131ba8caf4513ef7d3e19e474587e358c9a5101b21b48a77f6"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-b52a93a0a95f265a9210433a699efdae8289fd8beae04d45e0d39eaf1eb07786",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:b52a93a0a95f265a9210433a699efdae8289fd8beae04d45e0d39eaf1eb07786"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:b52a93a0a95f265a9210433a699efdae8289fd8beae04d45e0d39eaf1eb07786",
          "manifestHash": "sha256:7bdc63aa4889468447d30c2b0b07fad353cf51e24d8298022903024317bcca3d"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-default",
      "slug": "default",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "daily",
      "name": {
        "en": "Vibe Chat",
        "zh-CN": "默认 Chat"
      },
      "summary": {
        "en": "A calm, complete Chat App ready to use now and reshape with an Agent later.",
        "zh-CN": "创建后立即可用的完整 Chat App，之后可随时通过 Agent 改造成任何形态。"
      },
      "author": "VibeChat Kernel",
      "icon": "V",
      "accent": "#ff5a3d",
      "canvas": "#10120f",
      "currentVersionId": "tplv-space-default-0-1-5"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862",
          "manifestHash": "sha256:e35a482b9741bd3dda47cd968eb6b3f2947defd4797f94c77837dadf4fa3eece"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-824cf2c28a22bdc8990c3fbd14e29eb22afb1e524433e30e8e013bbca244b2a9",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:824cf2c28a22bdc8990c3fbd14e29eb22afb1e524433e30e8e013bbca244b2a9"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:824cf2c28a22bdc8990c3fbd14e29eb22afb1e524433e30e8e013bbca244b2a9",
          "manifestHash": "sha256:1abd89b4c6c2f34a3e800c79748cf2240e82af4646b28d7b076b792173b083c0"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-d16c43c9bc2b859306f266affd3f3baf8fda435d948f663efd5caa1b7037a22d",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:d16c43c9bc2b859306f266affd3f3baf8fda435d948f663efd5caa1b7037a22d"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:d16c43c9bc2b859306f266affd3f3baf8fda435d948f663efd5caa1b7037a22d",
          "manifestHash": "sha256:63776099424104dca62b6097d0710cdde2eaab9c661959820d1dd8722448ec38"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-3",
          "semanticVersion": "0.1.3",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-a3c634456525b7aab93ff3ade653e49832adb10eb05ba99c7dcde3a5a9211526",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:a3c634456525b7aab93ff3ade653e49832adb10eb05ba99c7dcde3a5a9211526"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:a3c634456525b7aab93ff3ade653e49832adb10eb05ba99c7dcde3a5a9211526",
          "manifestHash": "sha256:7a614d15d2d7c7ab07e93cad8b5a034ebfad78e91f8d5341dace417f9f1c2bca"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-4",
          "semanticVersion": "0.1.4",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-446fa544386fe4f1b95b8a6f6e99b1e3dc402f1544ea2b85eb2b9603610b09ce",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:446fa544386fe4f1b95b8a6f6e99b1e3dc402f1544ea2b85eb2b9603610b09ce"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:446fa544386fe4f1b95b8a6f6e99b1e3dc402f1544ea2b85eb2b9603610b09ce",
          "manifestHash": "sha256:b4384f73bac9a1bf48a57b1fd4146556f4f2596109c2615083eedc230916c691"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-5",
          "semanticVersion": "0.1.5",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-5e26e8fc2d6cf530bfff971b94029ba32d366cb90c8daf42d8115cc5ccce4449",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:5e26e8fc2d6cf530bfff971b94029ba32d366cb90c8daf42d8115cc5ccce4449"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:5e26e8fc2d6cf530bfff971b94029ba32d366cb90c8daf42d8115cc5ccce4449",
          "manifestHash": "sha256:8e3363f923328a46b9b668488d4a3753c6a8e214bd332b5a4646162a4f725dfa"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-focus",
      "slug": "focus",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "focus",
      "name": {
        "en": "Moss Studio",
        "zh-CN": "苔原共创室"
      },
      "summary": {
        "en": "A quiet co-creation table where messages settle like shared notes.",
        "zh-CN": "为小团队准备的安静共创 Space，消息会像便签一样落在共享桌面上。"
      },
      "author": "Field Notes Lab",
      "icon": "⌁",
      "accent": "#b7d66d",
      "canvas": "#23342b",
      "currentVersionId": "tplv-space-focus-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4",
          "manifestHash": "sha256:f973231703190595d1c3a93a502902bc1d04b91d53a8c677ae445067a0f01801"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-ed85c9023c1da8e42213976636a30f7a072634eb2be4de0fcaddfc98646721a9",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:ed85c9023c1da8e42213976636a30f7a072634eb2be4de0fcaddfc98646721a9"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:ed85c9023c1da8e42213976636a30f7a072634eb2be4de0fcaddfc98646721a9",
          "manifestHash": "sha256:9b4f5aa3d4cad2bbaf562032c082b652a3bde3f17b5a146f40d25c619b5b76ad"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-7fff7448e4ee0097a982854a00c053418d7abd4fd64a3f3d40c2c25e36f828a5",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:7fff7448e4ee0097a982854a00c053418d7abd4fd64a3f3d40c2c25e36f828a5"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:7fff7448e4ee0097a982854a00c053418d7abd4fd64a3f3d40c2c25e36f828a5",
          "manifestHash": "sha256:b60df96e08f669f04846c0c05f24bd421f80e57736c6b0e82a9a1e4bb91bec55"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-postcard",
      "slug": "postcard",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "ritual",
      "name": {
        "en": "Tomorrow Postcard",
        "zh-CN": "明日明信片"
      },
      "summary": {
        "en": "Send what you feel now to a future moment, then open it together.",
        "zh-CN": "把现在想说的话寄给未来，直到约定的时刻在 Space 里一起拆开。"
      },
      "author": "Vibe Chat Studio",
      "icon": "◇",
      "accent": "#d84b42",
      "canvas": "#efe5d2",
      "currentVersionId": "tplv-space-postcard-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b",
          "manifestHash": "sha256:44619280a5a78bebfe47a25a0034d5f73af79e3b51bae1c8caaad895225ca458"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-ec6df561b9c853359889df8b3066466212b99d7d964b00df475ba9a61da06127",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:ec6df561b9c853359889df8b3066466212b99d7d964b00df475ba9a61da06127"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:ec6df561b9c853359889df8b3066466212b99d7d964b00df475ba9a61da06127",
          "manifestHash": "sha256:eb977132fecd5a440f5ec163b6d6a2024e13a452fc72eddfe0aedbb4e0cfeafc"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-16ed93f878e3acc0b455ee78495c74edf423605d7276b2684b6e56b1d01b7e97",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:16ed93f878e3acc0b455ee78495c74edf423605d7276b2684b6e56b1d01b7e97"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:16ed93f878e3acc0b455ee78495c74edf423605d7276b2684b6e56b1d01b7e97",
          "manifestHash": "sha256:448fc8da2a9802ef6cdc617f3d1b05d74df525a55b3517c7442a7457aea73c47"
        }
      }
    ]
  }
] as const;
