// Generated by scripts/generate-official-catalog.mjs. Do not edit.
export const officialTemplateDefinitions = [
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-arcade",
      "slug": "arcade",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "play",
      "name": {
        "en": "Pixel Saturday",
        "zh-CN": "像素星期六"
      },
      "summary": {
        "en": "A handheld-console hangout where reactions become collectible pixel badges.",
        "zh-CN": "带一点掌机颗粒感的朋友 Space，互动会变成可以收集的像素徽章。"
      },
      "author": "8-Bit Picnic",
      "icon": "✦",
      "accent": "#ffd84d",
      "canvas": "#34274f",
      "currentVersionId": "tplv-space-arcade-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c",
          "manifestHash": "sha256:f31c6e092c2936f9de6de99b6161c7ae86737f58dc2b7aec220360a6ed03511e"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-cd8f14588018f1646aa6868075c5e58b13546c4581b5400dbcaeab2956c85019",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:cd8f14588018f1646aa6868075c5e58b13546c4581b5400dbcaeab2956c85019"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:cd8f14588018f1646aa6868075c5e58b13546c4581b5400dbcaeab2956c85019",
          "manifestHash": "sha256:99ee3fee6e2f573de8980795cfdd298ab788004bd1086cdc6722506eb8fe218c"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-68546cf15329416e61b06ea283b80aa292791c38fa59335b80b0674b7d7bbb3a",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:68546cf15329416e61b06ea283b80aa292791c38fa59335b80b0674b7d7bbb3a"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:68546cf15329416e61b06ea283b80aa292791c38fa59335b80b0674b7d7bbb3a",
          "manifestHash": "sha256:8a9b5bb834ac587d79ca17a1a6a110d894f6d4c4b5699f86b5ba3bf47f3c4704"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-campfire",
      "slug": "campfire",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "daily",
      "name": {
        "en": "Afterglow Radio",
        "zh-CN": "夜航电台"
      },
      "summary": {
        "en": "A slow-moving late-night radio Space for the last thoughts of the day.",
        "zh-CN": "像深夜电台一样缓慢流动的 Space，适合分享一天最后的心事。"
      },
      "author": "Vibe Chat Studio",
      "icon": "◐",
      "accent": "#ff6b42",
      "canvas": "#171b20",
      "currentVersionId": "tplv-space-campfire-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a",
          "manifestHash": "sha256:942824609f34c91a55bce3261ecd80babbd3130dbb495fe083f3c26c466d13ad"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-971b7254741afab05e47616b36a86d0ff512d777e6f8c3cb38b78bb2b2dd506b",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:971b7254741afab05e47616b36a86d0ff512d777e6f8c3cb38b78bb2b2dd506b"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:971b7254741afab05e47616b36a86d0ff512d777e6f8c3cb38b78bb2b2dd506b",
          "manifestHash": "sha256:56c721d600ffdf131ba8caf4513ef7d3e19e474587e358c9a5101b21b48a77f6"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-56061ec8ec8df5ecf6fbeaf1b386f24ea1bfb75ecb6805860f7b3ebf07564239",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:56061ec8ec8df5ecf6fbeaf1b386f24ea1bfb75ecb6805860f7b3ebf07564239"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:56061ec8ec8df5ecf6fbeaf1b386f24ea1bfb75ecb6805860f7b3ebf07564239",
          "manifestHash": "sha256:da5de896951bbe79a3a25726a70b1ae606a38148d9a230fef87046d22a526539"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-default",
      "slug": "default",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "daily",
      "name": {
        "en": "Vibe Chat",
        "zh-CN": "默认 Chat"
      },
      "summary": {
        "en": "A calm, complete Chat App ready to use now and reshape with an Agent later.",
        "zh-CN": "创建后立即可用的完整 Chat App，之后可随时通过 Agent 改造成任何形态。"
      },
      "author": "VibeChat Kernel",
      "icon": "V",
      "accent": "#ff5a3d",
      "canvas": "#10120f",
      "currentVersionId": "tplv-space-default-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862",
          "manifestHash": "sha256:e35a482b9741bd3dda47cd968eb6b3f2947defd4797f94c77837dadf4fa3eece"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-824cf2c28a22bdc8990c3fbd14e29eb22afb1e524433e30e8e013bbca244b2a9",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:824cf2c28a22bdc8990c3fbd14e29eb22afb1e524433e30e8e013bbca244b2a9"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:824cf2c28a22bdc8990c3fbd14e29eb22afb1e524433e30e8e013bbca244b2a9",
          "manifestHash": "sha256:1abd89b4c6c2f34a3e800c79748cf2240e82af4646b28d7b076b792173b083c0"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-33833e1254b21fb28427e3a057119a22866fffe5f8ea40e5cd7f296dc004d96b",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:33833e1254b21fb28427e3a057119a22866fffe5f8ea40e5cd7f296dc004d96b"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:33833e1254b21fb28427e3a057119a22866fffe5f8ea40e5cd7f296dc004d96b",
          "manifestHash": "sha256:b2d421db8a5af5646c5fd729a4b8fd1c7344f880543bb572459de9b99541dfb9"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-focus",
      "slug": "focus",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "focus",
      "name": {
        "en": "Moss Studio",
        "zh-CN": "苔原共创室"
      },
      "summary": {
        "en": "A quiet co-creation table where messages settle like shared notes.",
        "zh-CN": "为小团队准备的安静共创 Space，消息会像便签一样落在共享桌面上。"
      },
      "author": "Field Notes Lab",
      "icon": "⌁",
      "accent": "#b7d66d",
      "canvas": "#23342b",
      "currentVersionId": "tplv-space-focus-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4",
          "manifestHash": "sha256:f973231703190595d1c3a93a502902bc1d04b91d53a8c677ae445067a0f01801"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-ed85c9023c1da8e42213976636a30f7a072634eb2be4de0fcaddfc98646721a9",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:ed85c9023c1da8e42213976636a30f7a072634eb2be4de0fcaddfc98646721a9"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:ed85c9023c1da8e42213976636a30f7a072634eb2be4de0fcaddfc98646721a9",
          "manifestHash": "sha256:9b4f5aa3d4cad2bbaf562032c082b652a3bde3f17b5a146f40d25c619b5b76ad"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-033cee630fcf408955f093d8ccca28ef60b9ff6620c59df8dfbe4db1d8c2680a",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:033cee630fcf408955f093d8ccca28ef60b9ff6620c59df8dfbe4db1d8c2680a"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:033cee630fcf408955f093d8ccca28ef60b9ff6620c59df8dfbe4db1d8c2680a",
          "manifestHash": "sha256:8c06d1b9eabff62b3e2a31388ed87a9007d150912107fb0a7a1e424e08d4f13b"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-postcard",
      "slug": "postcard",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "ritual",
      "name": {
        "en": "Tomorrow Postcard",
        "zh-CN": "明日明信片"
      },
      "summary": {
        "en": "Send what you feel now to a future moment, then open it together.",
        "zh-CN": "把现在想说的话寄给未来，直到约定的时刻在 Space 里一起拆开。"
      },
      "author": "Vibe Chat Studio",
      "icon": "◇",
      "accent": "#d84b42",
      "canvas": "#efe5d2",
      "currentVersionId": "tplv-space-postcard-0-1-2"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b",
          "manifestHash": "sha256:44619280a5a78bebfe47a25a0034d5f73af79e3b51bae1c8caaad895225ca458"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-1",
          "semanticVersion": "0.1.1",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-ec6df561b9c853359889df8b3066466212b99d7d964b00df475ba9a61da06127",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:ec6df561b9c853359889df8b3066466212b99d7d964b00df475ba9a61da06127"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:ec6df561b9c853359889df8b3066466212b99d7d964b00df475ba9a61da06127",
          "manifestHash": "sha256:eb977132fecd5a440f5ec163b6d6a2024e13a452fc72eddfe0aedbb4e0cfeafc"
        }
      },
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-2",
          "semanticVersion": "0.1.2",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-bcb20cbe6b80978ea30e2ba5aea6ec906f1e8e1d19b337b1f6b8e5a88c35dd86",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:bcb20cbe6b80978ea30e2ba5aea6ec906f1e8e1d19b337b1f6b8e5a88c35dd86"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:bcb20cbe6b80978ea30e2ba5aea6ec906f1e8e1d19b337b1f6b8e5a88c35dd86",
          "manifestHash": "sha256:94adb1a05e79e17fa10df71c97d56d9590575826299bb590ec219d9734b5fef7"
        }
      }
    ]
  }
] as const;
