// Generated by scripts/generate-official-catalog.mjs. Do not edit.
export const officialTemplateDefinitions = [
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-arcade",
      "slug": "arcade",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "play",
      "name": {
        "en": "Pixel Saturday",
        "zh-CN": "像素星期六"
      },
      "summary": {
        "en": "A handheld-console hangout where reactions become collectible pixel badges.",
        "zh-CN": "带一点掌机颗粒感的朋友 Space，互动会变成可以收集的像素徽章。"
      },
      "author": "8-Bit Picnic",
      "icon": "✦",
      "accent": "#ffd84d",
      "canvas": "#34274f",
      "currentVersionId": "tplv-space-arcade-0-1-0"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-arcade-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-arcade/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:663d95dcfb4c3d2e4e36515e3cbfdfedbd4314c09a1a1438acb09bc6ae6edb9c",
          "manifestHash": "sha256:f31c6e092c2936f9de6de99b6161c7ae86737f58dc2b7aec220360a6ed03511e"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-campfire",
      "slug": "campfire",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "daily",
      "name": {
        "en": "Afterglow Radio",
        "zh-CN": "夜航电台"
      },
      "summary": {
        "en": "A slow-moving late-night radio Space for the last thoughts of the day.",
        "zh-CN": "像深夜电台一样缓慢流动的 Space，适合分享一天最后的心事。"
      },
      "author": "Vibe Chat Studio",
      "icon": "◐",
      "accent": "#ff6b42",
      "canvas": "#171b20",
      "currentVersionId": "tplv-space-campfire-0-1-0"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-campfire-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "interactions.send"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-campfire/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:bf176c6b8abbe6dbab8c8515a60f1ba49104219f75396b950cb39ab5de80715a",
          "manifestHash": "sha256:942824609f34c91a55bce3261ecd80babbd3130dbb495fe083f3c26c466d13ad"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-default",
      "slug": "default",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "daily",
      "name": {
        "en": "Vibe Chat",
        "zh-CN": "默认 Chat"
      },
      "summary": {
        "en": "A calm, complete Chat App ready to use now and reshape with an Agent later.",
        "zh-CN": "创建后立即可用的完整 Chat App，之后可随时通过 Agent 改造成任何形态。"
      },
      "author": "VibeChat Kernel",
      "icon": "V",
      "accent": "#ff5a3d",
      "canvas": "#10120f",
      "currentVersionId": "tplv-space-default-0-1-0"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-default-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "messages.manage-own",
              "mentions.read",
              "agents.invoke",
              "members.read"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-default/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:db4f6a1d4666f9e0902fe70f4798898070c348cad212111591783808ed505862",
          "manifestHash": "sha256:e35a482b9741bd3dda47cd968eb6b3f2947defd4797f94c77837dadf4fa3eece"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-focus",
      "slug": "focus",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "focus",
      "name": {
        "en": "Moss Studio",
        "zh-CN": "苔原共创室"
      },
      "summary": {
        "en": "A quiet co-creation table where messages settle like shared notes.",
        "zh-CN": "为小团队准备的安静共创 Space，消息会像便签一样落在共享桌面上。"
      },
      "author": "Field Notes Lab",
      "icon": "⌁",
      "accent": "#b7d66d",
      "canvas": "#23342b",
      "currentVersionId": "tplv-space-focus-0-1-0"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-focus-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-focus/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:e5a57b17aa162aa8124b1b41d8a610cd5f0eeff6c13685f2789d76b8ceabd9a4",
          "manifestHash": "sha256:f973231703190595d1c3a93a502902bc1d04b91d53a8c677ae445067a0f01801"
        }
      }
    ]
  },
  {
    "manifest": {
      "schemaVersion": "vibechat.space-template/v1",
      "id": "space-postcard",
      "slug": "postcard",
      "publisher": {
        "id": "publisher-vibechat",
        "displayName": "VibeChat",
        "verification": "official"
      },
      "category": "ritual",
      "name": {
        "en": "Tomorrow Postcard",
        "zh-CN": "明日明信片"
      },
      "summary": {
        "en": "Send what you feel now to a future moment, then open it together.",
        "zh-CN": "把现在想说的话寄给未来，直到约定的时刻在 Space 里一起拆开。"
      },
      "author": "Vibe Chat Studio",
      "icon": "◇",
      "accent": "#d84b42",
      "canvas": "#efe5d2",
      "currentVersionId": "tplv-space-postcard-0-1-0"
    },
    "versions": [
      {
        "manifest": {
          "schemaVersion": "vibechat.space-template-version/v1",
          "id": "tplv-space-postcard-0-1-0",
          "semanticVersion": "0.1.0",
          "projectFormat": "agentos-app-v1",
          "compatibility": {
            "spaceAppSdk": "v1",
            "runtime": "agentos-apps-0.2"
          },
          "capabilities": {
            "permissions": [
              "messages.read",
              "messages.send",
              "members.read",
              "state.shared.write"
            ],
            "networkDomains": []
          },
          "provenance": {
            "origin": "repository",
            "publisherId": "publisher-vibechat",
            "sourcePath": "packages/space-templates/official/space-postcard/app"
          }
        },
        "artifact": {
          "schemaVersion": "vibechat.space-template-artifact/v1",
          "id": "tpla-933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b",
          "format": "agentos-app-v1",
          "sourceHash": "sha256:933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b"
        },
        "lock": {
          "schemaVersion": "vibechat.space-template-version-lock/v1",
          "sourceHash": "sha256:933424a2a246da954c22a789109451b487e07a6cb1a57b7d7a1b1abd7995d30b",
          "manifestHash": "sha256:44619280a5a78bebfe47a25a0034d5f73af79e3b51bae1c8caaad895225ca458"
        }
      }
    ]
  }
] as const;
