/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as AdminWithdrawalsIndexRouteImport } from './routes/admin/withdrawals/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSubscriptionsIndexRouteImport } from './routes/admin/subscriptions/index'
import { Route as AdminPricingIndexRouteImport } from './routes/admin/pricing/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminCreditsIndexRouteImport } from './routes/admin/credits/index'
import { Route as AdminCommissionsIndexRouteImport } from './routes/admin/commissions/index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog/index'
import { Route as AdminAgentsIndexRouteImport } from './routes/admin/agents/index'
import { Route as AdminUsersIdIndexRouteImport } from './routes/admin/users/$id/index'
import { Route as AdminPricingIdIndexRouteImport } from './routes/admin/pricing/$id/index'
import { Route as AdminBlogIdIndexRouteImport } from './routes/admin/blog/$id/index'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)
const AdminWithdrawalsIndexRoute = AdminWithdrawalsIndexRouteImport.update({
  id: '/withdrawals/',
  path: '/withdrawals/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscriptionsIndexRoute = AdminSubscriptionsIndexRouteImport.update({
  id: '/subscriptions/',
  path: '/subscriptions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingIndexRoute = AdminPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreditsIndexRoute = AdminCreditsIndexRouteImport.update({
  id: '/credits/',
  path: '/credits/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommissionsIndexRoute = AdminCommissionsIndexRouteImport.update({
  id: '/commissions/',
  path: '/commissions/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsIndexRoute = AdminAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIdIndexRoute = AdminUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPricingIdIndexRoute = AdminPricingIdIndexRouteImport.update({
  id: '/pricing/$id/',
  path: '/pricing/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIdIndexRoute = AdminBlogIdIndexRouteImport.update({
  id: '/blog/$id/',
  path: '/blog/$id/',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/signin': typeof SigninRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/commissions/': typeof AdminCommissionsIndexRoute
  '/admin/credits/': typeof AdminCreditsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pricing/': typeof AdminPricingIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
  '/admin/blog/$id/': typeof AdminBlogIdIndexRoute
  '/admin/pricing/$id/': typeof AdminPricingIdIndexRoute
  '/admin/users/$id/': typeof AdminUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/$locale': typeof LocaleRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/signin': typeof SigninRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/agents': typeof AdminAgentsIndexRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/commissions': typeof AdminCommissionsIndexRoute
  '/admin/credits': typeof AdminCreditsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/pricing': typeof AdminPricingIndexRoute
  '/admin/subscriptions': typeof AdminSubscriptionsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/withdrawals': typeof AdminWithdrawalsIndexRoute
  '/admin/blog/$id': typeof AdminBlogIdIndexRoute
  '/admin/pricing/$id': typeof AdminPricingIdIndexRoute
  '/admin/users/$id': typeof AdminUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$locale': typeof LocaleRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/signin': typeof SigninRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/agents/': typeof AdminAgentsIndexRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/commissions/': typeof AdminCommissionsIndexRoute
  '/admin/credits/': typeof AdminCreditsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/pricing/': typeof AdminPricingIndexRoute
  '/admin/subscriptions/': typeof AdminSubscriptionsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/withdrawals/': typeof AdminWithdrawalsIndexRoute
  '/admin/blog/$id/': typeof AdminBlogIdIndexRoute
  '/admin/pricing/$id/': typeof AdminPricingIdIndexRoute
  '/admin/users/$id/': typeof AdminUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$locale'
    | '/admin'
    | '/forbidden'
    | '/signin'
    | '/$locale/$'
    | '/api/$'
    | '/admin/'
    | '/admin/agents/'
    | '/admin/blog/'
    | '/admin/commissions/'
    | '/admin/credits/'
    | '/admin/orders/'
    | '/admin/pricing/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/admin/withdrawals/'
    | '/admin/blog/$id/'
    | '/admin/pricing/$id/'
    | '/admin/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$locale'
    | '/forbidden'
    | '/signin'
    | '/$locale/$'
    | '/api/$'
    | '/admin'
    | '/admin/agents'
    | '/admin/blog'
    | '/admin/commissions'
    | '/admin/credits'
    | '/admin/orders'
    | '/admin/pricing'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/admin/blog/$id'
    | '/admin/pricing/$id'
    | '/admin/users/$id'
  id:
    | '__root__'
    | '/$locale'
    | '/admin'
    | '/forbidden'
    | '/signin'
    | '/$locale/$'
    | '/api/$'
    | '/admin/'
    | '/admin/agents/'
    | '/admin/blog/'
    | '/admin/commissions/'
    | '/admin/credits/'
    | '/admin/orders/'
    | '/admin/pricing/'
    | '/admin/subscriptions/'
    | '/admin/users/'
    | '/admin/withdrawals/'
    | '/admin/blog/$id/'
    | '/admin/pricing/$id/'
    | '/admin/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocaleRoute: typeof LocaleRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  SigninRoute: typeof SigninRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/admin/withdrawals/': {
      id: '/admin/withdrawals/'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals/'
      preLoaderRoute: typeof AdminWithdrawalsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscriptions/': {
      id: '/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions/'
      preLoaderRoute: typeof AdminSubscriptionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing/': {
      id: '/admin/pricing/'
      path: '/pricing'
      fullPath: '/admin/pricing/'
      preLoaderRoute: typeof AdminPricingIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/credits/': {
      id: '/admin/credits/'
      path: '/credits'
      fullPath: '/admin/credits/'
      preLoaderRoute: typeof AdminCreditsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/commissions/': {
      id: '/admin/commissions/'
      path: '/commissions'
      fullPath: '/admin/commissions/'
      preLoaderRoute: typeof AdminCommissionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents/': {
      id: '/admin/agents/'
      path: '/agents'
      fullPath: '/admin/agents/'
      preLoaderRoute: typeof AdminAgentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/$id/': {
      id: '/admin/users/$id/'
      path: '/users/$id'
      fullPath: '/admin/users/$id/'
      preLoaderRoute: typeof AdminUsersIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pricing/$id/': {
      id: '/admin/pricing/$id/'
      path: '/pricing/$id'
      fullPath: '/admin/pricing/$id/'
      preLoaderRoute: typeof AdminPricingIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id/': {
      id: '/admin/blog/$id/'
      path: '/blog/$id'
      fullPath: '/admin/blog/$id/'
      preLoaderRoute: typeof AdminBlogIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAgentsIndexRoute: typeof AdminAgentsIndexRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminCommissionsIndexRoute: typeof AdminCommissionsIndexRoute
  AdminCreditsIndexRoute: typeof AdminCreditsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPricingIndexRoute: typeof AdminPricingIndexRoute
  AdminSubscriptionsIndexRoute: typeof AdminSubscriptionsIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminWithdrawalsIndexRoute: typeof AdminWithdrawalsIndexRoute
  AdminBlogIdIndexRoute: typeof AdminBlogIdIndexRoute
  AdminPricingIdIndexRoute: typeof AdminPricingIdIndexRoute
  AdminUsersIdIndexRoute: typeof AdminUsersIdIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminAgentsIndexRoute: AdminAgentsIndexRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminCommissionsIndexRoute: AdminCommissionsIndexRoute,
  AdminCreditsIndexRoute: AdminCreditsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPricingIndexRoute: AdminPricingIndexRoute,
  AdminSubscriptionsIndexRoute: AdminSubscriptionsIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminWithdrawalsIndexRoute: AdminWithdrawalsIndexRoute,
  AdminBlogIdIndexRoute: AdminBlogIdIndexRoute,
  AdminPricingIdIndexRoute: AdminPricingIdIndexRoute,
  AdminUsersIdIndexRoute: AdminUsersIdIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LocaleRoute: LocaleRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  SigninRoute: SigninRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
