/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as LangSigninRouteImport } from './routes/$lang/signin'
import { Route as LangForbiddenRouteImport } from './routes/$lang/forbidden'
import { Route as LangAdminRouteImport } from './routes/$lang/admin'
import { Route as LangAdminIndexRouteImport } from './routes/$lang/admin/index'
import { Route as LangAdminWithdrawalsIndexRouteImport } from './routes/$lang/admin/withdrawals/index'
import { Route as LangAdminUsersIndexRouteImport } from './routes/$lang/admin/users/index'
import { Route as LangAdminSubscriptionsIndexRouteImport } from './routes/$lang/admin/subscriptions/index'
import { Route as LangAdminPricingIndexRouteImport } from './routes/$lang/admin/pricing/index'
import { Route as LangAdminOrdersIndexRouteImport } from './routes/$lang/admin/orders/index'
import { Route as LangAdminCreditsIndexRouteImport } from './routes/$lang/admin/credits/index'
import { Route as LangAdminCommissionsIndexRouteImport } from './routes/$lang/admin/commissions/index'
import { Route as LangAdminBlogIndexRouteImport } from './routes/$lang/admin/blog/index'
import { Route as LangAdminUsersIdIndexRouteImport } from './routes/$lang/admin/users/$id/index'
import { Route as LangAdminPricingIdIndexRouteImport } from './routes/$lang/admin/pricing/$id/index'
import { Route as LangAdminBlogIdIndexRouteImport } from './routes/$lang/admin/blog/$id/index'

const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSigninRoute = LangSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => LangRoute,
} as any)
const LangForbiddenRoute = LangForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminRoute = LangAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LangRoute,
} as any)
const LangAdminIndexRoute = LangAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminWithdrawalsIndexRoute =
  LangAdminWithdrawalsIndexRouteImport.update({
    id: '/withdrawals/',
    path: '/withdrawals/',
    getParentRoute: () => LangAdminRoute,
  } as any)
const LangAdminUsersIndexRoute = LangAdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminSubscriptionsIndexRoute =
  LangAdminSubscriptionsIndexRouteImport.update({
    id: '/subscriptions/',
    path: '/subscriptions/',
    getParentRoute: () => LangAdminRoute,
  } as any)
const LangAdminPricingIndexRoute = LangAdminPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminOrdersIndexRoute = LangAdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminCreditsIndexRoute = LangAdminCreditsIndexRouteImport.update({
  id: '/credits/',
  path: '/credits/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminCommissionsIndexRoute =
  LangAdminCommissionsIndexRouteImport.update({
    id: '/commissions/',
    path: '/commissions/',
    getParentRoute: () => LangAdminRoute,
  } as any)
const LangAdminBlogIndexRoute = LangAdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminUsersIdIndexRoute = LangAdminUsersIdIndexRouteImport.update({
  id: '/users/$id/',
  path: '/users/$id/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminPricingIdIndexRoute = LangAdminPricingIdIndexRouteImport.update({
  id: '/pricing/$id/',
  path: '/pricing/$id/',
  getParentRoute: () => LangAdminRoute,
} as any)
const LangAdminBlogIdIndexRoute = LangAdminBlogIdIndexRouteImport.update({
  id: '/blog/$id/',
  path: '/blog/$id/',
  getParentRoute: () => LangAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/forbidden': typeof LangForbiddenRoute
  '/$lang/signin': typeof LangSigninRoute
  '/api/$': typeof ApiSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/admin/blog/': typeof LangAdminBlogIndexRoute
  '/$lang/admin/commissions/': typeof LangAdminCommissionsIndexRoute
  '/$lang/admin/credits/': typeof LangAdminCreditsIndexRoute
  '/$lang/admin/orders/': typeof LangAdminOrdersIndexRoute
  '/$lang/admin/pricing/': typeof LangAdminPricingIndexRoute
  '/$lang/admin/subscriptions/': typeof LangAdminSubscriptionsIndexRoute
  '/$lang/admin/users/': typeof LangAdminUsersIndexRoute
  '/$lang/admin/withdrawals/': typeof LangAdminWithdrawalsIndexRoute
  '/$lang/admin/blog/$id/': typeof LangAdminBlogIdIndexRoute
  '/$lang/admin/pricing/$id/': typeof LangAdminPricingIdIndexRoute
  '/$lang/admin/users/$id/': typeof LangAdminUsersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$lang/forbidden': typeof LangForbiddenRoute
  '/$lang/signin': typeof LangSigninRoute
  '/api/$': typeof ApiSplatRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/admin': typeof LangAdminIndexRoute
  '/$lang/admin/blog': typeof LangAdminBlogIndexRoute
  '/$lang/admin/commissions': typeof LangAdminCommissionsIndexRoute
  '/$lang/admin/credits': typeof LangAdminCreditsIndexRoute
  '/$lang/admin/orders': typeof LangAdminOrdersIndexRoute
  '/$lang/admin/pricing': typeof LangAdminPricingIndexRoute
  '/$lang/admin/subscriptions': typeof LangAdminSubscriptionsIndexRoute
  '/$lang/admin/users': typeof LangAdminUsersIndexRoute
  '/$lang/admin/withdrawals': typeof LangAdminWithdrawalsIndexRoute
  '/$lang/admin/blog/$id': typeof LangAdminBlogIdIndexRoute
  '/$lang/admin/pricing/$id': typeof LangAdminPricingIdIndexRoute
  '/$lang/admin/users/$id': typeof LangAdminUsersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/admin': typeof LangAdminRouteWithChildren
  '/$lang/forbidden': typeof LangForbiddenRoute
  '/$lang/signin': typeof LangSigninRoute
  '/api/$': typeof ApiSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/admin/': typeof LangAdminIndexRoute
  '/$lang/admin/blog/': typeof LangAdminBlogIndexRoute
  '/$lang/admin/commissions/': typeof LangAdminCommissionsIndexRoute
  '/$lang/admin/credits/': typeof LangAdminCreditsIndexRoute
  '/$lang/admin/orders/': typeof LangAdminOrdersIndexRoute
  '/$lang/admin/pricing/': typeof LangAdminPricingIndexRoute
  '/$lang/admin/subscriptions/': typeof LangAdminSubscriptionsIndexRoute
  '/$lang/admin/users/': typeof LangAdminUsersIndexRoute
  '/$lang/admin/withdrawals/': typeof LangAdminWithdrawalsIndexRoute
  '/$lang/admin/blog/$id/': typeof LangAdminBlogIdIndexRoute
  '/$lang/admin/pricing/$id/': typeof LangAdminPricingIdIndexRoute
  '/$lang/admin/users/$id/': typeof LangAdminUsersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/forbidden'
    | '/$lang/signin'
    | '/api/$'
    | '/$lang/'
    | '/$lang/admin/'
    | '/$lang/admin/blog/'
    | '/$lang/admin/commissions/'
    | '/$lang/admin/credits/'
    | '/$lang/admin/orders/'
    | '/$lang/admin/pricing/'
    | '/$lang/admin/subscriptions/'
    | '/$lang/admin/users/'
    | '/$lang/admin/withdrawals/'
    | '/$lang/admin/blog/$id/'
    | '/$lang/admin/pricing/$id/'
    | '/$lang/admin/users/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$lang/forbidden'
    | '/$lang/signin'
    | '/api/$'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/admin/blog'
    | '/$lang/admin/commissions'
    | '/$lang/admin/credits'
    | '/$lang/admin/orders'
    | '/$lang/admin/pricing'
    | '/$lang/admin/subscriptions'
    | '/$lang/admin/users'
    | '/$lang/admin/withdrawals'
    | '/$lang/admin/blog/$id'
    | '/$lang/admin/pricing/$id'
    | '/$lang/admin/users/$id'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/$lang/admin'
    | '/$lang/forbidden'
    | '/$lang/signin'
    | '/api/$'
    | '/$lang/'
    | '/$lang/admin/'
    | '/$lang/admin/blog/'
    | '/$lang/admin/commissions/'
    | '/$lang/admin/credits/'
    | '/$lang/admin/orders/'
    | '/$lang/admin/pricing/'
    | '/$lang/admin/subscriptions/'
    | '/$lang/admin/users/'
    | '/$lang/admin/withdrawals/'
    | '/$lang/admin/blog/$id/'
    | '/$lang/admin/pricing/$id/'
    | '/$lang/admin/users/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/signin': {
      id: '/$lang/signin'
      path: '/signin'
      fullPath: '/$lang/signin'
      preLoaderRoute: typeof LangSigninRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/forbidden': {
      id: '/$lang/forbidden'
      path: '/forbidden'
      fullPath: '/$lang/forbidden'
      preLoaderRoute: typeof LangForbiddenRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin': {
      id: '/$lang/admin'
      path: '/admin'
      fullPath: '/$lang/admin'
      preLoaderRoute: typeof LangAdminRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/admin/': {
      id: '/$lang/admin/'
      path: '/'
      fullPath: '/$lang/admin/'
      preLoaderRoute: typeof LangAdminIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/withdrawals/': {
      id: '/$lang/admin/withdrawals/'
      path: '/withdrawals'
      fullPath: '/$lang/admin/withdrawals/'
      preLoaderRoute: typeof LangAdminWithdrawalsIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/users/': {
      id: '/$lang/admin/users/'
      path: '/users'
      fullPath: '/$lang/admin/users/'
      preLoaderRoute: typeof LangAdminUsersIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/subscriptions/': {
      id: '/$lang/admin/subscriptions/'
      path: '/subscriptions'
      fullPath: '/$lang/admin/subscriptions/'
      preLoaderRoute: typeof LangAdminSubscriptionsIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/pricing/': {
      id: '/$lang/admin/pricing/'
      path: '/pricing'
      fullPath: '/$lang/admin/pricing/'
      preLoaderRoute: typeof LangAdminPricingIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/orders/': {
      id: '/$lang/admin/orders/'
      path: '/orders'
      fullPath: '/$lang/admin/orders/'
      preLoaderRoute: typeof LangAdminOrdersIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/credits/': {
      id: '/$lang/admin/credits/'
      path: '/credits'
      fullPath: '/$lang/admin/credits/'
      preLoaderRoute: typeof LangAdminCreditsIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/commissions/': {
      id: '/$lang/admin/commissions/'
      path: '/commissions'
      fullPath: '/$lang/admin/commissions/'
      preLoaderRoute: typeof LangAdminCommissionsIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/blog/': {
      id: '/$lang/admin/blog/'
      path: '/blog'
      fullPath: '/$lang/admin/blog/'
      preLoaderRoute: typeof LangAdminBlogIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/users/$id/': {
      id: '/$lang/admin/users/$id/'
      path: '/users/$id'
      fullPath: '/$lang/admin/users/$id/'
      preLoaderRoute: typeof LangAdminUsersIdIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/pricing/$id/': {
      id: '/$lang/admin/pricing/$id/'
      path: '/pricing/$id'
      fullPath: '/$lang/admin/pricing/$id/'
      preLoaderRoute: typeof LangAdminPricingIdIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
    '/$lang/admin/blog/$id/': {
      id: '/$lang/admin/blog/$id/'
      path: '/blog/$id'
      fullPath: '/$lang/admin/blog/$id/'
      preLoaderRoute: typeof LangAdminBlogIdIndexRouteImport
      parentRoute: typeof LangAdminRoute
    }
  }
}

interface LangAdminRouteChildren {
  LangAdminIndexRoute: typeof LangAdminIndexRoute
  LangAdminBlogIndexRoute: typeof LangAdminBlogIndexRoute
  LangAdminCommissionsIndexRoute: typeof LangAdminCommissionsIndexRoute
  LangAdminCreditsIndexRoute: typeof LangAdminCreditsIndexRoute
  LangAdminOrdersIndexRoute: typeof LangAdminOrdersIndexRoute
  LangAdminPricingIndexRoute: typeof LangAdminPricingIndexRoute
  LangAdminSubscriptionsIndexRoute: typeof LangAdminSubscriptionsIndexRoute
  LangAdminUsersIndexRoute: typeof LangAdminUsersIndexRoute
  LangAdminWithdrawalsIndexRoute: typeof LangAdminWithdrawalsIndexRoute
  LangAdminBlogIdIndexRoute: typeof LangAdminBlogIdIndexRoute
  LangAdminPricingIdIndexRoute: typeof LangAdminPricingIdIndexRoute
  LangAdminUsersIdIndexRoute: typeof LangAdminUsersIdIndexRoute
}

const LangAdminRouteChildren: LangAdminRouteChildren = {
  LangAdminIndexRoute: LangAdminIndexRoute,
  LangAdminBlogIndexRoute: LangAdminBlogIndexRoute,
  LangAdminCommissionsIndexRoute: LangAdminCommissionsIndexRoute,
  LangAdminCreditsIndexRoute: LangAdminCreditsIndexRoute,
  LangAdminOrdersIndexRoute: LangAdminOrdersIndexRoute,
  LangAdminPricingIndexRoute: LangAdminPricingIndexRoute,
  LangAdminSubscriptionsIndexRoute: LangAdminSubscriptionsIndexRoute,
  LangAdminUsersIndexRoute: LangAdminUsersIndexRoute,
  LangAdminWithdrawalsIndexRoute: LangAdminWithdrawalsIndexRoute,
  LangAdminBlogIdIndexRoute: LangAdminBlogIdIndexRoute,
  LangAdminPricingIdIndexRoute: LangAdminPricingIdIndexRoute,
  LangAdminUsersIdIndexRoute: LangAdminUsersIdIndexRoute,
}

const LangAdminRouteWithChildren = LangAdminRoute._addFileChildren(
  LangAdminRouteChildren,
)

interface LangRouteChildren {
  LangAdminRoute: typeof LangAdminRouteWithChildren
  LangForbiddenRoute: typeof LangForbiddenRoute
  LangSigninRoute: typeof LangSigninRoute
  LangIndexRoute: typeof LangIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAdminRoute: LangAdminRouteWithChildren,
  LangForbiddenRoute: LangForbiddenRoute,
  LangSigninRoute: LangSigninRoute,
  LangIndexRoute: LangIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
