/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1SpaceAppSdkRouteImport } from './routes/v1/space-app-sdk'
import { Route as V1ProfileRouteImport } from './routes/v1/profile'
import { Route as V1ProductStateRouteImport } from './routes/v1/product-state'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiImageGenerateRouteImport } from './routes/api/image-generate'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as V1SpacesIndexRouteImport } from './routes/v1/spaces/index'
import { Route as V1RoomsIndexRouteImport } from './routes/v1/rooms/index'
import { Route as V1FriendRequestsIndexRouteImport } from './routes/v1/friend-requests/index'
import { Route as V1ContactsIndexRouteImport } from './routes/v1/contacts/index'
import { Route as V1BlocksIndexRouteImport } from './routes/v1/blocks/index'
import { Route as ApiVideoGenerateIndexRouteImport } from './routes/api/video-generate/index'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as V1UsersSearchRouteImport } from './routes/v1/users/search'
import { Route as V1SessionBootstrapRouteImport } from './routes/v1/session/bootstrap'
import { Route as V1RoomsMetadataRouteImport } from './routes/v1/rooms/metadata'
import { Route as V1InternalSpaceAgentBillingRouteImport } from './routes/v1/internal/space-agent-billing'
import { Route as V1ContactsUserIdRouteImport } from './routes/v1/contacts/$userId'
import { Route as V1BlocksUserIdRouteImport } from './routes/v1/blocks/$userId'
import { Route as ApiWithdrawalRequestRouteImport } from './routes/api/withdrawal/request'
import { Route as ApiWithdrawalHistoryRouteImport } from './routes/api/withdrawal/history'
import { Route as ApiVideoGenerateStatusRouteImport } from './routes/api/video-generate/status'
import { Route as ApiUsersIdRouteImport } from './routes/api/users/$id'
import { Route as ApiSubscriptionStatusRouteImport } from './routes/api/subscription/status'
import { Route as ApiSubscriptionPortalRouteImport } from './routes/api/subscription/portal'
import { Route as ApiPricingPlansRouteImport } from './routes/api/pricing/plans'
import { Route as ApiPaymentQueryRouteImport } from './routes/api/payment/query'
import { Route as ApiPaymentInitiateRouteImport } from './routes/api/payment/initiate'
import { Route as ApiPaymentCancelRouteImport } from './routes/api/payment/cancel'
import { Route as ApiCreditsTransactionsRouteImport } from './routes/api/credits/transactions'
import { Route as ApiCreditsStatusRouteImport } from './routes/api/credits/status'
import { Route as ApiCreditsBalanceRouteImport } from './routes/api/credits/balance'
import { Route as ApiBlogSlugRouteImport } from './routes/api/blog/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAffiliateStatsRouteImport } from './routes/api/affiliate/stats'
import { Route as ApiAffiliateReferralsRouteImport } from './routes/api/affiliate/referrals'
import { Route as ApiAffiliateCommissionsRouteImport } from './routes/api/affiliate/commissions'
import { Route as ApiAffiliateClaimRouteImport } from './routes/api/affiliate/claim'
import { Route as ApiAdminCommissionsRouteImport } from './routes/api/admin/commissions'
import { Route as ApiAdminWithdrawalsIndexRouteImport } from './routes/api/admin/withdrawals/index'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiAdminSubscriptionsIndexRouteImport } from './routes/api/admin/subscriptions/index'
import { Route as ApiAdminStatsIndexRouteImport } from './routes/api/admin/stats/index'
import { Route as ApiAdminPricingPlansIndexRouteImport } from './routes/api/admin/pricing-plans/index'
import { Route as ApiAdminOrdersIndexRouteImport } from './routes/api/admin/orders/index'
import { Route as ApiAdminBlogIndexRouteImport } from './routes/api/admin/blog/index'
import { Route as V1SpacesInstancesRoomIdRouteImport } from './routes/v1/spaces/instances/$roomId'
import { Route as V1SpacesSpaceIdFavoriteRouteImport } from './routes/v1/spaces/$spaceId/favorite'
import { Route as V1RoomsRoomIdPreferencesRouteImport } from './routes/v1/rooms/$roomId/preferences'
import { Route as V1FriendRequestsIdRejectRouteImport } from './routes/v1/friend-requests/$id/reject'
import { Route as V1FriendRequestsIdAcceptRouteImport } from './routes/v1/friend-requests/$id/accept'
import { Route as ApiPaymentWebhookWechatRouteImport } from './routes/api/payment/webhook/wechat'
import { Route as ApiPaymentWebhookStripeRouteImport } from './routes/api/payment/webhook/stripe'
import { Route as ApiPaymentWebhookPaypalRouteImport } from './routes/api/payment/webhook/paypal'
import { Route as ApiPaymentWebhookDodoRouteImport } from './routes/api/payment/webhook/dodo'
import { Route as ApiPaymentWebhookCreemRouteImport } from './routes/api/payment/webhook/creem'
import { Route as ApiPaymentWebhookAlipayRouteImport } from './routes/api/payment/webhook/alipay'
import { Route as ApiPaymentVerifyStripeRouteImport } from './routes/api/payment/verify/stripe'
import { Route as ApiPaymentVerifyCreemRouteImport } from './routes/api/payment/verify/creem'
import { Route as ApiPaymentReturnPaypalRouteImport } from './routes/api/payment/return/paypal'
import { Route as ApiAdminWithdrawalsIdRouteImport } from './routes/api/admin/withdrawals/$id'
import { Route as ApiAdminStatsMonthlyRouteImport } from './routes/api/admin/stats/monthly'
import { Route as ApiAdminPricingPlansReorderRouteImport } from './routes/api/admin/pricing-plans/reorder'
import { Route as ApiAdminPricingPlansImportRouteImport } from './routes/api/admin/pricing-plans/import'
import { Route as ApiAdminBlogIdRouteImport } from './routes/api/admin/blog/$id'
import { Route as ApiAdminUsersUpdateIndexRouteImport } from './routes/api/admin/users/update/index'
import { Route as ApiAdminUsersDeleteIndexRouteImport } from './routes/api/admin/users/delete/index'
import { Route as ApiAdminCreditsTransactionsIndexRouteImport } from './routes/api/admin/credits/transactions/index'
import { Route as V1SpacesInstancesRoomIdTurnsRouteImport } from './routes/v1/spaces/instances/$roomId/turns'
import { Route as V1SpacesInstancesRoomIdPublishRouteImport } from './routes/v1/spaces/instances/$roomId/publish'
import { Route as V1SpacesInstancesRoomIdEventsRouteImport } from './routes/v1/spaces/instances/$roomId/events'
import { Route as V1SpacesInstancesRoomIdBridgeRouteImport } from './routes/v1/spaces/instances/$roomId/bridge'
import { Route as V1SpacesInstancesRoomIdAppRouteImport } from './routes/v1/spaces/instances/$roomId/app'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SpaceAppSdkRoute = V1SpaceAppSdkRouteImport.update({
  id: '/v1/space-app-sdk',
  path: '/v1/space-app-sdk',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProfileRoute = V1ProfileRouteImport.update({
  id: '/v1/profile',
  path: '/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProductStateRoute = V1ProductStateRouteImport.update({
  id: '/v1/product-state',
  path: '/v1/product-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageGenerateRoute = ApiImageGenerateRouteImport.update({
  id: '/api/image-generate',
  path: '/api/image-generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SpacesIndexRoute = V1SpacesIndexRouteImport.update({
  id: '/v1/spaces/',
  path: '/v1/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RoomsIndexRoute = V1RoomsIndexRouteImport.update({
  id: '/v1/rooms/',
  path: '/v1/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1FriendRequestsIndexRoute = V1FriendRequestsIndexRouteImport.update({
  id: '/v1/friend-requests/',
  path: '/v1/friend-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ContactsIndexRoute = V1ContactsIndexRouteImport.update({
  id: '/v1/contacts/',
  path: '/v1/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1BlocksIndexRoute = V1BlocksIndexRouteImport.update({
  id: '/v1/blocks/',
  path: '/v1/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoGenerateIndexRoute = ApiVideoGenerateIndexRouteImport.update({
  id: '/api/video-generate/',
  path: '/api/video-generate/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1UsersSearchRoute = V1UsersSearchRouteImport.update({
  id: '/v1/users/search',
  path: '/v1/users/search',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SessionBootstrapRoute = V1SessionBootstrapRouteImport.update({
  id: '/v1/session/bootstrap',
  path: '/v1/session/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RoomsMetadataRoute = V1RoomsMetadataRouteImport.update({
  id: '/v1/rooms/metadata',
  path: '/v1/rooms/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const V1InternalSpaceAgentBillingRoute =
  V1InternalSpaceAgentBillingRouteImport.update({
    id: '/v1/internal/space-agent-billing',
    path: '/v1/internal/space-agent-billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1ContactsUserIdRoute = V1ContactsUserIdRouteImport.update({
  id: '/v1/contacts/$userId',
  path: '/v1/contacts/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1BlocksUserIdRoute = V1BlocksUserIdRouteImport.update({
  id: '/v1/blocks/$userId',
  path: '/v1/blocks/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawalRequestRoute = ApiWithdrawalRequestRouteImport.update({
  id: '/api/withdrawal/request',
  path: '/api/withdrawal/request',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWithdrawalHistoryRoute = ApiWithdrawalHistoryRouteImport.update({
  id: '/api/withdrawal/history',
  path: '/api/withdrawal/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoGenerateStatusRoute = ApiVideoGenerateStatusRouteImport.update({
  id: '/api/video-generate/status',
  path: '/api/video-generate/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersIdRoute = ApiUsersIdRouteImport.update({
  id: '/api/users/$id',
  path: '/api/users/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionStatusRoute = ApiSubscriptionStatusRouteImport.update({
  id: '/api/subscription/status',
  path: '/api/subscription/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscriptionPortalRoute = ApiSubscriptionPortalRouteImport.update({
  id: '/api/subscription/portal',
  path: '/api/subscription/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPricingPlansRoute = ApiPricingPlansRouteImport.update({
  id: '/api/pricing/plans',
  path: '/api/pricing/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentQueryRoute = ApiPaymentQueryRouteImport.update({
  id: '/api/payment/query',
  path: '/api/payment/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentInitiateRoute = ApiPaymentInitiateRouteImport.update({
  id: '/api/payment/initiate',
  path: '/api/payment/initiate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCancelRoute = ApiPaymentCancelRouteImport.update({
  id: '/api/payment/cancel',
  path: '/api/payment/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsTransactionsRoute = ApiCreditsTransactionsRouteImport.update({
  id: '/api/credits/transactions',
  path: '/api/credits/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsStatusRoute = ApiCreditsStatusRouteImport.update({
  id: '/api/credits/status',
  path: '/api/credits/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsBalanceRoute = ApiCreditsBalanceRouteImport.update({
  id: '/api/credits/balance',
  path: '/api/credits/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogSlugRoute = ApiBlogSlugRouteImport.update({
  id: '/api/blog/$slug',
  path: '/api/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateStatsRoute = ApiAffiliateStatsRouteImport.update({
  id: '/api/affiliate/stats',
  path: '/api/affiliate/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateReferralsRoute = ApiAffiliateReferralsRouteImport.update({
  id: '/api/affiliate/referrals',
  path: '/api/affiliate/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateCommissionsRoute = ApiAffiliateCommissionsRouteImport.update({
  id: '/api/affiliate/commissions',
  path: '/api/affiliate/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAffiliateClaimRoute = ApiAffiliateClaimRouteImport.update({
  id: '/api/affiliate/claim',
  path: '/api/affiliate/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCommissionsRoute = ApiAdminCommissionsRouteImport.update({
  id: '/api/admin/commissions',
  path: '/api/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWithdrawalsIndexRoute =
  ApiAdminWithdrawalsIndexRouteImport.update({
    id: '/api/admin/withdrawals/',
    path: '/api/admin/withdrawals/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscriptionsIndexRoute =
  ApiAdminSubscriptionsIndexRouteImport.update({
    id: '/api/admin/subscriptions/',
    path: '/api/admin/subscriptions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminStatsIndexRoute = ApiAdminStatsIndexRouteImport.update({
  id: '/api/admin/stats/',
  path: '/api/admin/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPricingPlansIndexRoute =
  ApiAdminPricingPlansIndexRouteImport.update({
    id: '/api/admin/pricing-plans/',
    path: '/api/admin/pricing-plans/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminOrdersIndexRoute = ApiAdminOrdersIndexRouteImport.update({
  id: '/api/admin/orders/',
  path: '/api/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlogIndexRoute = ApiAdminBlogIndexRouteImport.update({
  id: '/api/admin/blog/',
  path: '/api/admin/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SpacesInstancesRoomIdRoute = V1SpacesInstancesRoomIdRouteImport.update({
  id: '/v1/spaces/instances/$roomId',
  path: '/v1/spaces/instances/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SpacesSpaceIdFavoriteRoute = V1SpacesSpaceIdFavoriteRouteImport.update({
  id: '/v1/spaces/$spaceId/favorite',
  path: '/v1/spaces/$spaceId/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RoomsRoomIdPreferencesRoute =
  V1RoomsRoomIdPreferencesRouteImport.update({
    id: '/v1/rooms/$roomId/preferences',
    path: '/v1/rooms/$roomId/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1FriendRequestsIdRejectRoute =
  V1FriendRequestsIdRejectRouteImport.update({
    id: '/v1/friend-requests/$id/reject',
    path: '/v1/friend-requests/$id/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1FriendRequestsIdAcceptRoute =
  V1FriendRequestsIdAcceptRouteImport.update({
    id: '/v1/friend-requests/$id/accept',
    path: '/v1/friend-requests/$id/accept',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentWebhookWechatRoute = ApiPaymentWebhookWechatRouteImport.update({
  id: '/api/payment/webhook/wechat',
  path: '/api/payment/webhook/wechat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookStripeRoute = ApiPaymentWebhookStripeRouteImport.update({
  id: '/api/payment/webhook/stripe',
  path: '/api/payment/webhook/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookPaypalRoute = ApiPaymentWebhookPaypalRouteImport.update({
  id: '/api/payment/webhook/paypal',
  path: '/api/payment/webhook/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookDodoRoute = ApiPaymentWebhookDodoRouteImport.update({
  id: '/api/payment/webhook/dodo',
  path: '/api/payment/webhook/dodo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookCreemRoute = ApiPaymentWebhookCreemRouteImport.update({
  id: '/api/payment/webhook/creem',
  path: '/api/payment/webhook/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookAlipayRoute = ApiPaymentWebhookAlipayRouteImport.update({
  id: '/api/payment/webhook/alipay',
  path: '/api/payment/webhook/alipay',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentVerifyStripeRoute = ApiPaymentVerifyStripeRouteImport.update({
  id: '/api/payment/verify/stripe',
  path: '/api/payment/verify/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentVerifyCreemRoute = ApiPaymentVerifyCreemRouteImport.update({
  id: '/api/payment/verify/creem',
  path: '/api/payment/verify/creem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentReturnPaypalRoute = ApiPaymentReturnPaypalRouteImport.update({
  id: '/api/payment/return/paypal',
  path: '/api/payment/return/paypal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminWithdrawalsIdRoute = ApiAdminWithdrawalsIdRouteImport.update({
  id: '/api/admin/withdrawals/$id',
  path: '/api/admin/withdrawals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsMonthlyRoute = ApiAdminStatsMonthlyRouteImport.update({
  id: '/api/admin/stats/monthly',
  path: '/api/admin/stats/monthly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPricingPlansReorderRoute =
  ApiAdminPricingPlansReorderRouteImport.update({
    id: '/api/admin/pricing-plans/reorder',
    path: '/api/admin/pricing-plans/reorder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminPricingPlansImportRoute =
  ApiAdminPricingPlansImportRouteImport.update({
    id: '/api/admin/pricing-plans/import',
    path: '/api/admin/pricing-plans/import',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminBlogIdRoute = ApiAdminBlogIdRouteImport.update({
  id: '/api/admin/blog/$id',
  path: '/api/admin/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersUpdateIndexRoute =
  ApiAdminUsersUpdateIndexRouteImport.update({
    id: '/api/admin/users/update/',
    path: '/api/admin/users/update/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersDeleteIndexRoute =
  ApiAdminUsersDeleteIndexRouteImport.update({
    id: '/api/admin/users/delete/',
    path: '/api/admin/users/delete/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCreditsTransactionsIndexRoute =
  ApiAdminCreditsTransactionsIndexRouteImport.update({
    id: '/api/admin/credits/transactions/',
    path: '/api/admin/credits/transactions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1SpacesInstancesRoomIdTurnsRoute =
  V1SpacesInstancesRoomIdTurnsRouteImport.update({
    id: '/turns',
    path: '/turns',
    getParentRoute: () => V1SpacesInstancesRoomIdRoute,
  } as any)
const V1SpacesInstancesRoomIdPublishRoute =
  V1SpacesInstancesRoomIdPublishRouteImport.update({
    id: '/publish',
    path: '/publish',
    getParentRoute: () => V1SpacesInstancesRoomIdRoute,
  } as any)
const V1SpacesInstancesRoomIdEventsRoute =
  V1SpacesInstancesRoomIdEventsRouteImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => V1SpacesInstancesRoomIdRoute,
  } as any)
const V1SpacesInstancesRoomIdBridgeRoute =
  V1SpacesInstancesRoomIdBridgeRouteImport.update({
    id: '/bridge',
    path: '/bridge',
    getParentRoute: () => V1SpacesInstancesRoomIdRoute,
  } as any)
const V1SpacesInstancesRoomIdAppRoute =
  V1SpacesInstancesRoomIdAppRouteImport.update({
    id: '/app',
    path: '/app',
    getParentRoute: () => V1SpacesInstancesRoomIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/image-generate': typeof ApiImageGenerateRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/upload': typeof ApiUploadRoute
  '/v1/product-state': typeof V1ProductStateRoute
  '/v1/profile': typeof V1ProfileRoute
  '/v1/space-app-sdk': typeof V1SpaceAppSdkRoute
  '/api/admin/commissions': typeof ApiAdminCommissionsRoute
  '/api/affiliate/claim': typeof ApiAffiliateClaimRoute
  '/api/affiliate/commissions': typeof ApiAffiliateCommissionsRoute
  '/api/affiliate/referrals': typeof ApiAffiliateReferralsRoute
  '/api/affiliate/stats': typeof ApiAffiliateStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/credits/balance': typeof ApiCreditsBalanceRoute
  '/api/credits/status': typeof ApiCreditsStatusRoute
  '/api/credits/transactions': typeof ApiCreditsTransactionsRoute
  '/api/payment/cancel': typeof ApiPaymentCancelRoute
  '/api/payment/initiate': typeof ApiPaymentInitiateRoute
  '/api/payment/query': typeof ApiPaymentQueryRoute
  '/api/pricing/plans': typeof ApiPricingPlansRoute
  '/api/subscription/portal': typeof ApiSubscriptionPortalRoute
  '/api/subscription/status': typeof ApiSubscriptionStatusRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/video-generate/status': typeof ApiVideoGenerateStatusRoute
  '/api/withdrawal/history': typeof ApiWithdrawalHistoryRoute
  '/api/withdrawal/request': typeof ApiWithdrawalRequestRoute
  '/v1/blocks/$userId': typeof V1BlocksUserIdRoute
  '/v1/contacts/$userId': typeof V1ContactsUserIdRoute
  '/v1/internal/space-agent-billing': typeof V1InternalSpaceAgentBillingRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/session/bootstrap': typeof V1SessionBootstrapRoute
  '/v1/users/search': typeof V1UsersSearchRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/video-generate/': typeof ApiVideoGenerateIndexRoute
  '/v1/blocks/': typeof V1BlocksIndexRoute
  '/v1/contacts/': typeof V1ContactsIndexRoute
  '/v1/friend-requests/': typeof V1FriendRequestsIndexRoute
  '/v1/rooms/': typeof V1RoomsIndexRoute
  '/v1/spaces/': typeof V1SpacesIndexRoute
  '/api/admin/blog/$id': typeof ApiAdminBlogIdRoute
  '/api/admin/pricing-plans/import': typeof ApiAdminPricingPlansImportRoute
  '/api/admin/pricing-plans/reorder': typeof ApiAdminPricingPlansReorderRoute
  '/api/admin/stats/monthly': typeof ApiAdminStatsMonthlyRoute
  '/api/admin/withdrawals/$id': typeof ApiAdminWithdrawalsIdRoute
  '/api/payment/return/paypal': typeof ApiPaymentReturnPaypalRoute
  '/api/payment/verify/creem': typeof ApiPaymentVerifyCreemRoute
  '/api/payment/verify/stripe': typeof ApiPaymentVerifyStripeRoute
  '/api/payment/webhook/alipay': typeof ApiPaymentWebhookAlipayRoute
  '/api/payment/webhook/creem': typeof ApiPaymentWebhookCreemRoute
  '/api/payment/webhook/dodo': typeof ApiPaymentWebhookDodoRoute
  '/api/payment/webhook/paypal': typeof ApiPaymentWebhookPaypalRoute
  '/api/payment/webhook/stripe': typeof ApiPaymentWebhookStripeRoute
  '/api/payment/webhook/wechat': typeof ApiPaymentWebhookWechatRoute
  '/v1/friend-requests/$id/accept': typeof V1FriendRequestsIdAcceptRoute
  '/v1/friend-requests/$id/reject': typeof V1FriendRequestsIdRejectRoute
  '/v1/rooms/$roomId/preferences': typeof V1RoomsRoomIdPreferencesRoute
  '/v1/spaces/$spaceId/favorite': typeof V1SpacesSpaceIdFavoriteRoute
  '/v1/spaces/instances/$roomId': typeof V1SpacesInstancesRoomIdRouteWithChildren
  '/api/admin/blog/': typeof ApiAdminBlogIndexRoute
  '/api/admin/orders/': typeof ApiAdminOrdersIndexRoute
  '/api/admin/pricing-plans/': typeof ApiAdminPricingPlansIndexRoute
  '/api/admin/stats/': typeof ApiAdminStatsIndexRoute
  '/api/admin/subscriptions/': typeof ApiAdminSubscriptionsIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/admin/withdrawals/': typeof ApiAdminWithdrawalsIndexRoute
  '/v1/spaces/instances/$roomId/app': typeof V1SpacesInstancesRoomIdAppRoute
  '/v1/spaces/instances/$roomId/bridge': typeof V1SpacesInstancesRoomIdBridgeRoute
  '/v1/spaces/instances/$roomId/events': typeof V1SpacesInstancesRoomIdEventsRoute
  '/v1/spaces/instances/$roomId/publish': typeof V1SpacesInstancesRoomIdPublishRoute
  '/v1/spaces/instances/$roomId/turns': typeof V1SpacesInstancesRoomIdTurnsRoute
  '/api/admin/credits/transactions/': typeof ApiAdminCreditsTransactionsIndexRoute
  '/api/admin/users/delete/': typeof ApiAdminUsersDeleteIndexRoute
  '/api/admin/users/update/': typeof ApiAdminUsersUpdateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/image-generate': typeof ApiImageGenerateRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/upload': typeof ApiUploadRoute
  '/v1/product-state': typeof V1ProductStateRoute
  '/v1/profile': typeof V1ProfileRoute
  '/v1/space-app-sdk': typeof V1SpaceAppSdkRoute
  '/api/admin/commissions': typeof ApiAdminCommissionsRoute
  '/api/affiliate/claim': typeof ApiAffiliateClaimRoute
  '/api/affiliate/commissions': typeof ApiAffiliateCommissionsRoute
  '/api/affiliate/referrals': typeof ApiAffiliateReferralsRoute
  '/api/affiliate/stats': typeof ApiAffiliateStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/credits/balance': typeof ApiCreditsBalanceRoute
  '/api/credits/status': typeof ApiCreditsStatusRoute
  '/api/credits/transactions': typeof ApiCreditsTransactionsRoute
  '/api/payment/cancel': typeof ApiPaymentCancelRoute
  '/api/payment/initiate': typeof ApiPaymentInitiateRoute
  '/api/payment/query': typeof ApiPaymentQueryRoute
  '/api/pricing/plans': typeof ApiPricingPlansRoute
  '/api/subscription/portal': typeof ApiSubscriptionPortalRoute
  '/api/subscription/status': typeof ApiSubscriptionStatusRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/video-generate/status': typeof ApiVideoGenerateStatusRoute
  '/api/withdrawal/history': typeof ApiWithdrawalHistoryRoute
  '/api/withdrawal/request': typeof ApiWithdrawalRequestRoute
  '/v1/blocks/$userId': typeof V1BlocksUserIdRoute
  '/v1/contacts/$userId': typeof V1ContactsUserIdRoute
  '/v1/internal/space-agent-billing': typeof V1InternalSpaceAgentBillingRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/session/bootstrap': typeof V1SessionBootstrapRoute
  '/v1/users/search': typeof V1UsersSearchRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/api/video-generate': typeof ApiVideoGenerateIndexRoute
  '/v1/blocks': typeof V1BlocksIndexRoute
  '/v1/contacts': typeof V1ContactsIndexRoute
  '/v1/friend-requests': typeof V1FriendRequestsIndexRoute
  '/v1/rooms': typeof V1RoomsIndexRoute
  '/v1/spaces': typeof V1SpacesIndexRoute
  '/api/admin/blog/$id': typeof ApiAdminBlogIdRoute
  '/api/admin/pricing-plans/import': typeof ApiAdminPricingPlansImportRoute
  '/api/admin/pricing-plans/reorder': typeof ApiAdminPricingPlansReorderRoute
  '/api/admin/stats/monthly': typeof ApiAdminStatsMonthlyRoute
  '/api/admin/withdrawals/$id': typeof ApiAdminWithdrawalsIdRoute
  '/api/payment/return/paypal': typeof ApiPaymentReturnPaypalRoute
  '/api/payment/verify/creem': typeof ApiPaymentVerifyCreemRoute
  '/api/payment/verify/stripe': typeof ApiPaymentVerifyStripeRoute
  '/api/payment/webhook/alipay': typeof ApiPaymentWebhookAlipayRoute
  '/api/payment/webhook/creem': typeof ApiPaymentWebhookCreemRoute
  '/api/payment/webhook/dodo': typeof ApiPaymentWebhookDodoRoute
  '/api/payment/webhook/paypal': typeof ApiPaymentWebhookPaypalRoute
  '/api/payment/webhook/stripe': typeof ApiPaymentWebhookStripeRoute
  '/api/payment/webhook/wechat': typeof ApiPaymentWebhookWechatRoute
  '/v1/friend-requests/$id/accept': typeof V1FriendRequestsIdAcceptRoute
  '/v1/friend-requests/$id/reject': typeof V1FriendRequestsIdRejectRoute
  '/v1/rooms/$roomId/preferences': typeof V1RoomsRoomIdPreferencesRoute
  '/v1/spaces/$spaceId/favorite': typeof V1SpacesSpaceIdFavoriteRoute
  '/v1/spaces/instances/$roomId': typeof V1SpacesInstancesRoomIdRouteWithChildren
  '/api/admin/blog': typeof ApiAdminBlogIndexRoute
  '/api/admin/orders': typeof ApiAdminOrdersIndexRoute
  '/api/admin/pricing-plans': typeof ApiAdminPricingPlansIndexRoute
  '/api/admin/stats': typeof ApiAdminStatsIndexRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/admin/withdrawals': typeof ApiAdminWithdrawalsIndexRoute
  '/v1/spaces/instances/$roomId/app': typeof V1SpacesInstancesRoomIdAppRoute
  '/v1/spaces/instances/$roomId/bridge': typeof V1SpacesInstancesRoomIdBridgeRoute
  '/v1/spaces/instances/$roomId/events': typeof V1SpacesInstancesRoomIdEventsRoute
  '/v1/spaces/instances/$roomId/publish': typeof V1SpacesInstancesRoomIdPublishRoute
  '/v1/spaces/instances/$roomId/turns': typeof V1SpacesInstancesRoomIdTurnsRoute
  '/api/admin/credits/transactions': typeof ApiAdminCreditsTransactionsIndexRoute
  '/api/admin/users/delete': typeof ApiAdminUsersDeleteIndexRoute
  '/api/admin/users/update': typeof ApiAdminUsersUpdateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/health': typeof ApiHealthRoute
  '/api/image-generate': typeof ApiImageGenerateRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/upload': typeof ApiUploadRoute
  '/v1/product-state': typeof V1ProductStateRoute
  '/v1/profile': typeof V1ProfileRoute
  '/v1/space-app-sdk': typeof V1SpaceAppSdkRoute
  '/api/admin/commissions': typeof ApiAdminCommissionsRoute
  '/api/affiliate/claim': typeof ApiAffiliateClaimRoute
  '/api/affiliate/commissions': typeof ApiAffiliateCommissionsRoute
  '/api/affiliate/referrals': typeof ApiAffiliateReferralsRoute
  '/api/affiliate/stats': typeof ApiAffiliateStatsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/api/credits/balance': typeof ApiCreditsBalanceRoute
  '/api/credits/status': typeof ApiCreditsStatusRoute
  '/api/credits/transactions': typeof ApiCreditsTransactionsRoute
  '/api/payment/cancel': typeof ApiPaymentCancelRoute
  '/api/payment/initiate': typeof ApiPaymentInitiateRoute
  '/api/payment/query': typeof ApiPaymentQueryRoute
  '/api/pricing/plans': typeof ApiPricingPlansRoute
  '/api/subscription/portal': typeof ApiSubscriptionPortalRoute
  '/api/subscription/status': typeof ApiSubscriptionStatusRoute
  '/api/users/$id': typeof ApiUsersIdRoute
  '/api/video-generate/status': typeof ApiVideoGenerateStatusRoute
  '/api/withdrawal/history': typeof ApiWithdrawalHistoryRoute
  '/api/withdrawal/request': typeof ApiWithdrawalRequestRoute
  '/v1/blocks/$userId': typeof V1BlocksUserIdRoute
  '/v1/contacts/$userId': typeof V1ContactsUserIdRoute
  '/v1/internal/space-agent-billing': typeof V1InternalSpaceAgentBillingRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/session/bootstrap': typeof V1SessionBootstrapRoute
  '/v1/users/search': typeof V1UsersSearchRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/api/video-generate/': typeof ApiVideoGenerateIndexRoute
  '/v1/blocks/': typeof V1BlocksIndexRoute
  '/v1/contacts/': typeof V1ContactsIndexRoute
  '/v1/friend-requests/': typeof V1FriendRequestsIndexRoute
  '/v1/rooms/': typeof V1RoomsIndexRoute
  '/v1/spaces/': typeof V1SpacesIndexRoute
  '/api/admin/blog/$id': typeof ApiAdminBlogIdRoute
  '/api/admin/pricing-plans/import': typeof ApiAdminPricingPlansImportRoute
  '/api/admin/pricing-plans/reorder': typeof ApiAdminPricingPlansReorderRoute
  '/api/admin/stats/monthly': typeof ApiAdminStatsMonthlyRoute
  '/api/admin/withdrawals/$id': typeof ApiAdminWithdrawalsIdRoute
  '/api/payment/return/paypal': typeof ApiPaymentReturnPaypalRoute
  '/api/payment/verify/creem': typeof ApiPaymentVerifyCreemRoute
  '/api/payment/verify/stripe': typeof ApiPaymentVerifyStripeRoute
  '/api/payment/webhook/alipay': typeof ApiPaymentWebhookAlipayRoute
  '/api/payment/webhook/creem': typeof ApiPaymentWebhookCreemRoute
  '/api/payment/webhook/dodo': typeof ApiPaymentWebhookDodoRoute
  '/api/payment/webhook/paypal': typeof ApiPaymentWebhookPaypalRoute
  '/api/payment/webhook/stripe': typeof ApiPaymentWebhookStripeRoute
  '/api/payment/webhook/wechat': typeof ApiPaymentWebhookWechatRoute
  '/v1/friend-requests/$id/accept': typeof V1FriendRequestsIdAcceptRoute
  '/v1/friend-requests/$id/reject': typeof V1FriendRequestsIdRejectRoute
  '/v1/rooms/$roomId/preferences': typeof V1RoomsRoomIdPreferencesRoute
  '/v1/spaces/$spaceId/favorite': typeof V1SpacesSpaceIdFavoriteRoute
  '/v1/spaces/instances/$roomId': typeof V1SpacesInstancesRoomIdRouteWithChildren
  '/api/admin/blog/': typeof ApiAdminBlogIndexRoute
  '/api/admin/orders/': typeof ApiAdminOrdersIndexRoute
  '/api/admin/pricing-plans/': typeof ApiAdminPricingPlansIndexRoute
  '/api/admin/stats/': typeof ApiAdminStatsIndexRoute
  '/api/admin/subscriptions/': typeof ApiAdminSubscriptionsIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/admin/withdrawals/': typeof ApiAdminWithdrawalsIndexRoute
  '/v1/spaces/instances/$roomId/app': typeof V1SpacesInstancesRoomIdAppRoute
  '/v1/spaces/instances/$roomId/bridge': typeof V1SpacesInstancesRoomIdBridgeRoute
  '/v1/spaces/instances/$roomId/events': typeof V1SpacesInstancesRoomIdEventsRoute
  '/v1/spaces/instances/$roomId/publish': typeof V1SpacesInstancesRoomIdPublishRoute
  '/v1/spaces/instances/$roomId/turns': typeof V1SpacesInstancesRoomIdTurnsRoute
  '/api/admin/credits/transactions/': typeof ApiAdminCreditsTransactionsIndexRoute
  '/api/admin/users/delete/': typeof ApiAdminUsersDeleteIndexRoute
  '/api/admin/users/update/': typeof ApiAdminUsersUpdateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/image-generate'
    | '/api/orders'
    | '/api/upload'
    | '/v1/product-state'
    | '/v1/profile'
    | '/v1/space-app-sdk'
    | '/api/admin/commissions'
    | '/api/affiliate/claim'
    | '/api/affiliate/commissions'
    | '/api/affiliate/referrals'
    | '/api/affiliate/stats'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/api/credits/balance'
    | '/api/credits/status'
    | '/api/credits/transactions'
    | '/api/payment/cancel'
    | '/api/payment/initiate'
    | '/api/payment/query'
    | '/api/pricing/plans'
    | '/api/subscription/portal'
    | '/api/subscription/status'
    | '/api/users/$id'
    | '/api/video-generate/status'
    | '/api/withdrawal/history'
    | '/api/withdrawal/request'
    | '/v1/blocks/$userId'
    | '/v1/contacts/$userId'
    | '/v1/internal/space-agent-billing'
    | '/v1/rooms/metadata'
    | '/v1/session/bootstrap'
    | '/v1/users/search'
    | '/api/blog/'
    | '/api/video-generate/'
    | '/v1/blocks/'
    | '/v1/contacts/'
    | '/v1/friend-requests/'
    | '/v1/rooms/'
    | '/v1/spaces/'
    | '/api/admin/blog/$id'
    | '/api/admin/pricing-plans/import'
    | '/api/admin/pricing-plans/reorder'
    | '/api/admin/stats/monthly'
    | '/api/admin/withdrawals/$id'
    | '/api/payment/return/paypal'
    | '/api/payment/verify/creem'
    | '/api/payment/verify/stripe'
    | '/api/payment/webhook/alipay'
    | '/api/payment/webhook/creem'
    | '/api/payment/webhook/dodo'
    | '/api/payment/webhook/paypal'
    | '/api/payment/webhook/stripe'
    | '/api/payment/webhook/wechat'
    | '/v1/friend-requests/$id/accept'
    | '/v1/friend-requests/$id/reject'
    | '/v1/rooms/$roomId/preferences'
    | '/v1/spaces/$spaceId/favorite'
    | '/v1/spaces/instances/$roomId'
    | '/api/admin/blog/'
    | '/api/admin/orders/'
    | '/api/admin/pricing-plans/'
    | '/api/admin/stats/'
    | '/api/admin/subscriptions/'
    | '/api/admin/users/'
    | '/api/admin/withdrawals/'
    | '/v1/spaces/instances/$roomId/app'
    | '/v1/spaces/instances/$roomId/bridge'
    | '/v1/spaces/instances/$roomId/events'
    | '/v1/spaces/instances/$roomId/publish'
    | '/v1/spaces/instances/$roomId/turns'
    | '/api/admin/credits/transactions/'
    | '/api/admin/users/delete/'
    | '/api/admin/users/update/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/image-generate'
    | '/api/orders'
    | '/api/upload'
    | '/v1/product-state'
    | '/v1/profile'
    | '/v1/space-app-sdk'
    | '/api/admin/commissions'
    | '/api/affiliate/claim'
    | '/api/affiliate/commissions'
    | '/api/affiliate/referrals'
    | '/api/affiliate/stats'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/api/credits/balance'
    | '/api/credits/status'
    | '/api/credits/transactions'
    | '/api/payment/cancel'
    | '/api/payment/initiate'
    | '/api/payment/query'
    | '/api/pricing/plans'
    | '/api/subscription/portal'
    | '/api/subscription/status'
    | '/api/users/$id'
    | '/api/video-generate/status'
    | '/api/withdrawal/history'
    | '/api/withdrawal/request'
    | '/v1/blocks/$userId'
    | '/v1/contacts/$userId'
    | '/v1/internal/space-agent-billing'
    | '/v1/rooms/metadata'
    | '/v1/session/bootstrap'
    | '/v1/users/search'
    | '/api/blog'
    | '/api/video-generate'
    | '/v1/blocks'
    | '/v1/contacts'
    | '/v1/friend-requests'
    | '/v1/rooms'
    | '/v1/spaces'
    | '/api/admin/blog/$id'
    | '/api/admin/pricing-plans/import'
    | '/api/admin/pricing-plans/reorder'
    | '/api/admin/stats/monthly'
    | '/api/admin/withdrawals/$id'
    | '/api/payment/return/paypal'
    | '/api/payment/verify/creem'
    | '/api/payment/verify/stripe'
    | '/api/payment/webhook/alipay'
    | '/api/payment/webhook/creem'
    | '/api/payment/webhook/dodo'
    | '/api/payment/webhook/paypal'
    | '/api/payment/webhook/stripe'
    | '/api/payment/webhook/wechat'
    | '/v1/friend-requests/$id/accept'
    | '/v1/friend-requests/$id/reject'
    | '/v1/rooms/$roomId/preferences'
    | '/v1/spaces/$spaceId/favorite'
    | '/v1/spaces/instances/$roomId'
    | '/api/admin/blog'
    | '/api/admin/orders'
    | '/api/admin/pricing-plans'
    | '/api/admin/stats'
    | '/api/admin/subscriptions'
    | '/api/admin/users'
    | '/api/admin/withdrawals'
    | '/v1/spaces/instances/$roomId/app'
    | '/v1/spaces/instances/$roomId/bridge'
    | '/v1/spaces/instances/$roomId/events'
    | '/v1/spaces/instances/$roomId/publish'
    | '/v1/spaces/instances/$roomId/turns'
    | '/api/admin/credits/transactions'
    | '/api/admin/users/delete'
    | '/api/admin/users/update'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/health'
    | '/api/image-generate'
    | '/api/orders'
    | '/api/upload'
    | '/v1/product-state'
    | '/v1/profile'
    | '/v1/space-app-sdk'
    | '/api/admin/commissions'
    | '/api/affiliate/claim'
    | '/api/affiliate/commissions'
    | '/api/affiliate/referrals'
    | '/api/affiliate/stats'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/api/credits/balance'
    | '/api/credits/status'
    | '/api/credits/transactions'
    | '/api/payment/cancel'
    | '/api/payment/initiate'
    | '/api/payment/query'
    | '/api/pricing/plans'
    | '/api/subscription/portal'
    | '/api/subscription/status'
    | '/api/users/$id'
    | '/api/video-generate/status'
    | '/api/withdrawal/history'
    | '/api/withdrawal/request'
    | '/v1/blocks/$userId'
    | '/v1/contacts/$userId'
    | '/v1/internal/space-agent-billing'
    | '/v1/rooms/metadata'
    | '/v1/session/bootstrap'
    | '/v1/users/search'
    | '/api/blog/'
    | '/api/video-generate/'
    | '/v1/blocks/'
    | '/v1/contacts/'
    | '/v1/friend-requests/'
    | '/v1/rooms/'
    | '/v1/spaces/'
    | '/api/admin/blog/$id'
    | '/api/admin/pricing-plans/import'
    | '/api/admin/pricing-plans/reorder'
    | '/api/admin/stats/monthly'
    | '/api/admin/withdrawals/$id'
    | '/api/payment/return/paypal'
    | '/api/payment/verify/creem'
    | '/api/payment/verify/stripe'
    | '/api/payment/webhook/alipay'
    | '/api/payment/webhook/creem'
    | '/api/payment/webhook/dodo'
    | '/api/payment/webhook/paypal'
    | '/api/payment/webhook/stripe'
    | '/api/payment/webhook/wechat'
    | '/v1/friend-requests/$id/accept'
    | '/v1/friend-requests/$id/reject'
    | '/v1/rooms/$roomId/preferences'
    | '/v1/spaces/$spaceId/favorite'
    | '/v1/spaces/instances/$roomId'
    | '/api/admin/blog/'
    | '/api/admin/orders/'
    | '/api/admin/pricing-plans/'
    | '/api/admin/stats/'
    | '/api/admin/subscriptions/'
    | '/api/admin/users/'
    | '/api/admin/withdrawals/'
    | '/v1/spaces/instances/$roomId/app'
    | '/v1/spaces/instances/$roomId/bridge'
    | '/v1/spaces/instances/$roomId/events'
    | '/v1/spaces/instances/$roomId/publish'
    | '/v1/spaces/instances/$roomId/turns'
    | '/api/admin/credits/transactions/'
    | '/api/admin/users/delete/'
    | '/api/admin/users/update/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiImageGenerateRoute: typeof ApiImageGenerateRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiUploadRoute: typeof ApiUploadRoute
  V1ProductStateRoute: typeof V1ProductStateRoute
  V1ProfileRoute: typeof V1ProfileRoute
  V1SpaceAppSdkRoute: typeof V1SpaceAppSdkRoute
  ApiAdminCommissionsRoute: typeof ApiAdminCommissionsRoute
  ApiAffiliateClaimRoute: typeof ApiAffiliateClaimRoute
  ApiAffiliateCommissionsRoute: typeof ApiAffiliateCommissionsRoute
  ApiAffiliateReferralsRoute: typeof ApiAffiliateReferralsRoute
  ApiAffiliateStatsRoute: typeof ApiAffiliateStatsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlogSlugRoute: typeof ApiBlogSlugRoute
  ApiCreditsBalanceRoute: typeof ApiCreditsBalanceRoute
  ApiCreditsStatusRoute: typeof ApiCreditsStatusRoute
  ApiCreditsTransactionsRoute: typeof ApiCreditsTransactionsRoute
  ApiPaymentCancelRoute: typeof ApiPaymentCancelRoute
  ApiPaymentInitiateRoute: typeof ApiPaymentInitiateRoute
  ApiPaymentQueryRoute: typeof ApiPaymentQueryRoute
  ApiPricingPlansRoute: typeof ApiPricingPlansRoute
  ApiSubscriptionPortalRoute: typeof ApiSubscriptionPortalRoute
  ApiSubscriptionStatusRoute: typeof ApiSubscriptionStatusRoute
  ApiUsersIdRoute: typeof ApiUsersIdRoute
  ApiVideoGenerateStatusRoute: typeof ApiVideoGenerateStatusRoute
  ApiWithdrawalHistoryRoute: typeof ApiWithdrawalHistoryRoute
  ApiWithdrawalRequestRoute: typeof ApiWithdrawalRequestRoute
  V1BlocksUserIdRoute: typeof V1BlocksUserIdRoute
  V1ContactsUserIdRoute: typeof V1ContactsUserIdRoute
  V1InternalSpaceAgentBillingRoute: typeof V1InternalSpaceAgentBillingRoute
  V1RoomsMetadataRoute: typeof V1RoomsMetadataRoute
  V1SessionBootstrapRoute: typeof V1SessionBootstrapRoute
  V1UsersSearchRoute: typeof V1UsersSearchRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
  ApiVideoGenerateIndexRoute: typeof ApiVideoGenerateIndexRoute
  V1BlocksIndexRoute: typeof V1BlocksIndexRoute
  V1ContactsIndexRoute: typeof V1ContactsIndexRoute
  V1FriendRequestsIndexRoute: typeof V1FriendRequestsIndexRoute
  V1RoomsIndexRoute: typeof V1RoomsIndexRoute
  V1SpacesIndexRoute: typeof V1SpacesIndexRoute
  ApiAdminBlogIdRoute: typeof ApiAdminBlogIdRoute
  ApiAdminPricingPlansImportRoute: typeof ApiAdminPricingPlansImportRoute
  ApiAdminPricingPlansReorderRoute: typeof ApiAdminPricingPlansReorderRoute
  ApiAdminStatsMonthlyRoute: typeof ApiAdminStatsMonthlyRoute
  ApiAdminWithdrawalsIdRoute: typeof ApiAdminWithdrawalsIdRoute
  ApiPaymentReturnPaypalRoute: typeof ApiPaymentReturnPaypalRoute
  ApiPaymentVerifyCreemRoute: typeof ApiPaymentVerifyCreemRoute
  ApiPaymentVerifyStripeRoute: typeof ApiPaymentVerifyStripeRoute
  ApiPaymentWebhookAlipayRoute: typeof ApiPaymentWebhookAlipayRoute
  ApiPaymentWebhookCreemRoute: typeof ApiPaymentWebhookCreemRoute
  ApiPaymentWebhookDodoRoute: typeof ApiPaymentWebhookDodoRoute
  ApiPaymentWebhookPaypalRoute: typeof ApiPaymentWebhookPaypalRoute
  ApiPaymentWebhookStripeRoute: typeof ApiPaymentWebhookStripeRoute
  ApiPaymentWebhookWechatRoute: typeof ApiPaymentWebhookWechatRoute
  V1FriendRequestsIdAcceptRoute: typeof V1FriendRequestsIdAcceptRoute
  V1FriendRequestsIdRejectRoute: typeof V1FriendRequestsIdRejectRoute
  V1RoomsRoomIdPreferencesRoute: typeof V1RoomsRoomIdPreferencesRoute
  V1SpacesSpaceIdFavoriteRoute: typeof V1SpacesSpaceIdFavoriteRoute
  V1SpacesInstancesRoomIdRoute: typeof V1SpacesInstancesRoomIdRouteWithChildren
  ApiAdminBlogIndexRoute: typeof ApiAdminBlogIndexRoute
  ApiAdminOrdersIndexRoute: typeof ApiAdminOrdersIndexRoute
  ApiAdminPricingPlansIndexRoute: typeof ApiAdminPricingPlansIndexRoute
  ApiAdminStatsIndexRoute: typeof ApiAdminStatsIndexRoute
  ApiAdminSubscriptionsIndexRoute: typeof ApiAdminSubscriptionsIndexRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
  ApiAdminWithdrawalsIndexRoute: typeof ApiAdminWithdrawalsIndexRoute
  ApiAdminCreditsTransactionsIndexRoute: typeof ApiAdminCreditsTransactionsIndexRoute
  ApiAdminUsersDeleteIndexRoute: typeof ApiAdminUsersDeleteIndexRoute
  ApiAdminUsersUpdateIndexRoute: typeof ApiAdminUsersUpdateIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/space-app-sdk': {
      id: '/v1/space-app-sdk'
      path: '/v1/space-app-sdk'
      fullPath: '/v1/space-app-sdk'
      preLoaderRoute: typeof V1SpaceAppSdkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/profile': {
      id: '/v1/profile'
      path: '/v1/profile'
      fullPath: '/v1/profile'
      preLoaderRoute: typeof V1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/product-state': {
      id: '/v1/product-state'
      path: '/v1/product-state'
      fullPath: '/v1/product-state'
      preLoaderRoute: typeof V1ProductStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image-generate': {
      id: '/api/image-generate'
      path: '/api/image-generate'
      fullPath: '/api/image-generate'
      preLoaderRoute: typeof ApiImageGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/spaces/': {
      id: '/v1/spaces/'
      path: '/v1/spaces'
      fullPath: '/v1/spaces/'
      preLoaderRoute: typeof V1SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/rooms/': {
      id: '/v1/rooms/'
      path: '/v1/rooms'
      fullPath: '/v1/rooms/'
      preLoaderRoute: typeof V1RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/friend-requests/': {
      id: '/v1/friend-requests/'
      path: '/v1/friend-requests'
      fullPath: '/v1/friend-requests/'
      preLoaderRoute: typeof V1FriendRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/contacts/': {
      id: '/v1/contacts/'
      path: '/v1/contacts'
      fullPath: '/v1/contacts/'
      preLoaderRoute: typeof V1ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/blocks/': {
      id: '/v1/blocks/'
      path: '/v1/blocks'
      fullPath: '/v1/blocks/'
      preLoaderRoute: typeof V1BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-generate/': {
      id: '/api/video-generate/'
      path: '/api/video-generate'
      fullPath: '/api/video-generate/'
      preLoaderRoute: typeof ApiVideoGenerateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/users/search': {
      id: '/v1/users/search'
      path: '/v1/users/search'
      fullPath: '/v1/users/search'
      preLoaderRoute: typeof V1UsersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/session/bootstrap': {
      id: '/v1/session/bootstrap'
      path: '/v1/session/bootstrap'
      fullPath: '/v1/session/bootstrap'
      preLoaderRoute: typeof V1SessionBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/rooms/metadata': {
      id: '/v1/rooms/metadata'
      path: '/v1/rooms/metadata'
      fullPath: '/v1/rooms/metadata'
      preLoaderRoute: typeof V1RoomsMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/internal/space-agent-billing': {
      id: '/v1/internal/space-agent-billing'
      path: '/v1/internal/space-agent-billing'
      fullPath: '/v1/internal/space-agent-billing'
      preLoaderRoute: typeof V1InternalSpaceAgentBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/contacts/$userId': {
      id: '/v1/contacts/$userId'
      path: '/v1/contacts/$userId'
      fullPath: '/v1/contacts/$userId'
      preLoaderRoute: typeof V1ContactsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/blocks/$userId': {
      id: '/v1/blocks/$userId'
      path: '/v1/blocks/$userId'
      fullPath: '/v1/blocks/$userId'
      preLoaderRoute: typeof V1BlocksUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdrawal/request': {
      id: '/api/withdrawal/request'
      path: '/api/withdrawal/request'
      fullPath: '/api/withdrawal/request'
      preLoaderRoute: typeof ApiWithdrawalRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/withdrawal/history': {
      id: '/api/withdrawal/history'
      path: '/api/withdrawal/history'
      fullPath: '/api/withdrawal/history'
      preLoaderRoute: typeof ApiWithdrawalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video-generate/status': {
      id: '/api/video-generate/status'
      path: '/api/video-generate/status'
      fullPath: '/api/video-generate/status'
      preLoaderRoute: typeof ApiVideoGenerateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/$id': {
      id: '/api/users/$id'
      path: '/api/users/$id'
      fullPath: '/api/users/$id'
      preLoaderRoute: typeof ApiUsersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription/status': {
      id: '/api/subscription/status'
      path: '/api/subscription/status'
      fullPath: '/api/subscription/status'
      preLoaderRoute: typeof ApiSubscriptionStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscription/portal': {
      id: '/api/subscription/portal'
      path: '/api/subscription/portal'
      fullPath: '/api/subscription/portal'
      preLoaderRoute: typeof ApiSubscriptionPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pricing/plans': {
      id: '/api/pricing/plans'
      path: '/api/pricing/plans'
      fullPath: '/api/pricing/plans'
      preLoaderRoute: typeof ApiPricingPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/query': {
      id: '/api/payment/query'
      path: '/api/payment/query'
      fullPath: '/api/payment/query'
      preLoaderRoute: typeof ApiPaymentQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/initiate': {
      id: '/api/payment/initiate'
      path: '/api/payment/initiate'
      fullPath: '/api/payment/initiate'
      preLoaderRoute: typeof ApiPaymentInitiateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/cancel': {
      id: '/api/payment/cancel'
      path: '/api/payment/cancel'
      fullPath: '/api/payment/cancel'
      preLoaderRoute: typeof ApiPaymentCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/transactions': {
      id: '/api/credits/transactions'
      path: '/api/credits/transactions'
      fullPath: '/api/credits/transactions'
      preLoaderRoute: typeof ApiCreditsTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/status': {
      id: '/api/credits/status'
      path: '/api/credits/status'
      fullPath: '/api/credits/status'
      preLoaderRoute: typeof ApiCreditsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits/balance': {
      id: '/api/credits/balance'
      path: '/api/credits/balance'
      fullPath: '/api/credits/balance'
      preLoaderRoute: typeof ApiCreditsBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$slug': {
      id: '/api/blog/$slug'
      path: '/api/blog/$slug'
      fullPath: '/api/blog/$slug'
      preLoaderRoute: typeof ApiBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate/stats': {
      id: '/api/affiliate/stats'
      path: '/api/affiliate/stats'
      fullPath: '/api/affiliate/stats'
      preLoaderRoute: typeof ApiAffiliateStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate/referrals': {
      id: '/api/affiliate/referrals'
      path: '/api/affiliate/referrals'
      fullPath: '/api/affiliate/referrals'
      preLoaderRoute: typeof ApiAffiliateReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate/commissions': {
      id: '/api/affiliate/commissions'
      path: '/api/affiliate/commissions'
      fullPath: '/api/affiliate/commissions'
      preLoaderRoute: typeof ApiAffiliateCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/affiliate/claim': {
      id: '/api/affiliate/claim'
      path: '/api/affiliate/claim'
      fullPath: '/api/affiliate/claim'
      preLoaderRoute: typeof ApiAffiliateClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/commissions': {
      id: '/api/admin/commissions'
      path: '/api/admin/commissions'
      fullPath: '/api/admin/commissions'
      preLoaderRoute: typeof ApiAdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/withdrawals/': {
      id: '/api/admin/withdrawals/'
      path: '/api/admin/withdrawals'
      fullPath: '/api/admin/withdrawals/'
      preLoaderRoute: typeof ApiAdminWithdrawalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users/'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscriptions/': {
      id: '/api/admin/subscriptions/'
      path: '/api/admin/subscriptions'
      fullPath: '/api/admin/subscriptions/'
      preLoaderRoute: typeof ApiAdminSubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats/': {
      id: '/api/admin/stats/'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats/'
      preLoaderRoute: typeof ApiAdminStatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing-plans/': {
      id: '/api/admin/pricing-plans/'
      path: '/api/admin/pricing-plans'
      fullPath: '/api/admin/pricing-plans/'
      preLoaderRoute: typeof ApiAdminPricingPlansIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders/': {
      id: '/api/admin/orders/'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders/'
      preLoaderRoute: typeof ApiAdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blog/': {
      id: '/api/admin/blog/'
      path: '/api/admin/blog'
      fullPath: '/api/admin/blog/'
      preLoaderRoute: typeof ApiAdminBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/spaces/instances/$roomId': {
      id: '/v1/spaces/instances/$roomId'
      path: '/v1/spaces/instances/$roomId'
      fullPath: '/v1/spaces/instances/$roomId'
      preLoaderRoute: typeof V1SpacesInstancesRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/spaces/$spaceId/favorite': {
      id: '/v1/spaces/$spaceId/favorite'
      path: '/v1/spaces/$spaceId/favorite'
      fullPath: '/v1/spaces/$spaceId/favorite'
      preLoaderRoute: typeof V1SpacesSpaceIdFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/rooms/$roomId/preferences': {
      id: '/v1/rooms/$roomId/preferences'
      path: '/v1/rooms/$roomId/preferences'
      fullPath: '/v1/rooms/$roomId/preferences'
      preLoaderRoute: typeof V1RoomsRoomIdPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/friend-requests/$id/reject': {
      id: '/v1/friend-requests/$id/reject'
      path: '/v1/friend-requests/$id/reject'
      fullPath: '/v1/friend-requests/$id/reject'
      preLoaderRoute: typeof V1FriendRequestsIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/friend-requests/$id/accept': {
      id: '/v1/friend-requests/$id/accept'
      path: '/v1/friend-requests/$id/accept'
      fullPath: '/v1/friend-requests/$id/accept'
      preLoaderRoute: typeof V1FriendRequestsIdAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/wechat': {
      id: '/api/payment/webhook/wechat'
      path: '/api/payment/webhook/wechat'
      fullPath: '/api/payment/webhook/wechat'
      preLoaderRoute: typeof ApiPaymentWebhookWechatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/stripe': {
      id: '/api/payment/webhook/stripe'
      path: '/api/payment/webhook/stripe'
      fullPath: '/api/payment/webhook/stripe'
      preLoaderRoute: typeof ApiPaymentWebhookStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/paypal': {
      id: '/api/payment/webhook/paypal'
      path: '/api/payment/webhook/paypal'
      fullPath: '/api/payment/webhook/paypal'
      preLoaderRoute: typeof ApiPaymentWebhookPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/dodo': {
      id: '/api/payment/webhook/dodo'
      path: '/api/payment/webhook/dodo'
      fullPath: '/api/payment/webhook/dodo'
      preLoaderRoute: typeof ApiPaymentWebhookDodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/creem': {
      id: '/api/payment/webhook/creem'
      path: '/api/payment/webhook/creem'
      fullPath: '/api/payment/webhook/creem'
      preLoaderRoute: typeof ApiPaymentWebhookCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook/alipay': {
      id: '/api/payment/webhook/alipay'
      path: '/api/payment/webhook/alipay'
      fullPath: '/api/payment/webhook/alipay'
      preLoaderRoute: typeof ApiPaymentWebhookAlipayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/verify/stripe': {
      id: '/api/payment/verify/stripe'
      path: '/api/payment/verify/stripe'
      fullPath: '/api/payment/verify/stripe'
      preLoaderRoute: typeof ApiPaymentVerifyStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/verify/creem': {
      id: '/api/payment/verify/creem'
      path: '/api/payment/verify/creem'
      fullPath: '/api/payment/verify/creem'
      preLoaderRoute: typeof ApiPaymentVerifyCreemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/return/paypal': {
      id: '/api/payment/return/paypal'
      path: '/api/payment/return/paypal'
      fullPath: '/api/payment/return/paypal'
      preLoaderRoute: typeof ApiPaymentReturnPaypalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/withdrawals/$id': {
      id: '/api/admin/withdrawals/$id'
      path: '/api/admin/withdrawals/$id'
      fullPath: '/api/admin/withdrawals/$id'
      preLoaderRoute: typeof ApiAdminWithdrawalsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats/monthly': {
      id: '/api/admin/stats/monthly'
      path: '/api/admin/stats/monthly'
      fullPath: '/api/admin/stats/monthly'
      preLoaderRoute: typeof ApiAdminStatsMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing-plans/reorder': {
      id: '/api/admin/pricing-plans/reorder'
      path: '/api/admin/pricing-plans/reorder'
      fullPath: '/api/admin/pricing-plans/reorder'
      preLoaderRoute: typeof ApiAdminPricingPlansReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/pricing-plans/import': {
      id: '/api/admin/pricing-plans/import'
      path: '/api/admin/pricing-plans/import'
      fullPath: '/api/admin/pricing-plans/import'
      preLoaderRoute: typeof ApiAdminPricingPlansImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blog/$id': {
      id: '/api/admin/blog/$id'
      path: '/api/admin/blog/$id'
      fullPath: '/api/admin/blog/$id'
      preLoaderRoute: typeof ApiAdminBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/update/': {
      id: '/api/admin/users/update/'
      path: '/api/admin/users/update'
      fullPath: '/api/admin/users/update/'
      preLoaderRoute: typeof ApiAdminUsersUpdateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/delete/': {
      id: '/api/admin/users/delete/'
      path: '/api/admin/users/delete'
      fullPath: '/api/admin/users/delete/'
      preLoaderRoute: typeof ApiAdminUsersDeleteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/credits/transactions/': {
      id: '/api/admin/credits/transactions/'
      path: '/api/admin/credits/transactions'
      fullPath: '/api/admin/credits/transactions/'
      preLoaderRoute: typeof ApiAdminCreditsTransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/spaces/instances/$roomId/turns': {
      id: '/v1/spaces/instances/$roomId/turns'
      path: '/turns'
      fullPath: '/v1/spaces/instances/$roomId/turns'
      preLoaderRoute: typeof V1SpacesInstancesRoomIdTurnsRouteImport
      parentRoute: typeof V1SpacesInstancesRoomIdRoute
    }
    '/v1/spaces/instances/$roomId/publish': {
      id: '/v1/spaces/instances/$roomId/publish'
      path: '/publish'
      fullPath: '/v1/spaces/instances/$roomId/publish'
      preLoaderRoute: typeof V1SpacesInstancesRoomIdPublishRouteImport
      parentRoute: typeof V1SpacesInstancesRoomIdRoute
    }
    '/v1/spaces/instances/$roomId/events': {
      id: '/v1/spaces/instances/$roomId/events'
      path: '/events'
      fullPath: '/v1/spaces/instances/$roomId/events'
      preLoaderRoute: typeof V1SpacesInstancesRoomIdEventsRouteImport
      parentRoute: typeof V1SpacesInstancesRoomIdRoute
    }
    '/v1/spaces/instances/$roomId/bridge': {
      id: '/v1/spaces/instances/$roomId/bridge'
      path: '/bridge'
      fullPath: '/v1/spaces/instances/$roomId/bridge'
      preLoaderRoute: typeof V1SpacesInstancesRoomIdBridgeRouteImport
      parentRoute: typeof V1SpacesInstancesRoomIdRoute
    }
    '/v1/spaces/instances/$roomId/app': {
      id: '/v1/spaces/instances/$roomId/app'
      path: '/app'
      fullPath: '/v1/spaces/instances/$roomId/app'
      preLoaderRoute: typeof V1SpacesInstancesRoomIdAppRouteImport
      parentRoute: typeof V1SpacesInstancesRoomIdRoute
    }
  }
}

interface V1SpacesInstancesRoomIdRouteChildren {
  V1SpacesInstancesRoomIdAppRoute: typeof V1SpacesInstancesRoomIdAppRoute
  V1SpacesInstancesRoomIdBridgeRoute: typeof V1SpacesInstancesRoomIdBridgeRoute
  V1SpacesInstancesRoomIdEventsRoute: typeof V1SpacesInstancesRoomIdEventsRoute
  V1SpacesInstancesRoomIdPublishRoute: typeof V1SpacesInstancesRoomIdPublishRoute
  V1SpacesInstancesRoomIdTurnsRoute: typeof V1SpacesInstancesRoomIdTurnsRoute
}

const V1SpacesInstancesRoomIdRouteChildren: V1SpacesInstancesRoomIdRouteChildren =
  {
    V1SpacesInstancesRoomIdAppRoute: V1SpacesInstancesRoomIdAppRoute,
    V1SpacesInstancesRoomIdBridgeRoute: V1SpacesInstancesRoomIdBridgeRoute,
    V1SpacesInstancesRoomIdEventsRoute: V1SpacesInstancesRoomIdEventsRoute,
    V1SpacesInstancesRoomIdPublishRoute: V1SpacesInstancesRoomIdPublishRoute,
    V1SpacesInstancesRoomIdTurnsRoute: V1SpacesInstancesRoomIdTurnsRoute,
  }

const V1SpacesInstancesRoomIdRouteWithChildren =
  V1SpacesInstancesRoomIdRoute._addFileChildren(
    V1SpacesInstancesRoomIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiImageGenerateRoute: ApiImageGenerateRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiUploadRoute: ApiUploadRoute,
  V1ProductStateRoute: V1ProductStateRoute,
  V1ProfileRoute: V1ProfileRoute,
  V1SpaceAppSdkRoute: V1SpaceAppSdkRoute,
  ApiAdminCommissionsRoute: ApiAdminCommissionsRoute,
  ApiAffiliateClaimRoute: ApiAffiliateClaimRoute,
  ApiAffiliateCommissionsRoute: ApiAffiliateCommissionsRoute,
  ApiAffiliateReferralsRoute: ApiAffiliateReferralsRoute,
  ApiAffiliateStatsRoute: ApiAffiliateStatsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlogSlugRoute: ApiBlogSlugRoute,
  ApiCreditsBalanceRoute: ApiCreditsBalanceRoute,
  ApiCreditsStatusRoute: ApiCreditsStatusRoute,
  ApiCreditsTransactionsRoute: ApiCreditsTransactionsRoute,
  ApiPaymentCancelRoute: ApiPaymentCancelRoute,
  ApiPaymentInitiateRoute: ApiPaymentInitiateRoute,
  ApiPaymentQueryRoute: ApiPaymentQueryRoute,
  ApiPricingPlansRoute: ApiPricingPlansRoute,
  ApiSubscriptionPortalRoute: ApiSubscriptionPortalRoute,
  ApiSubscriptionStatusRoute: ApiSubscriptionStatusRoute,
  ApiUsersIdRoute: ApiUsersIdRoute,
  ApiVideoGenerateStatusRoute: ApiVideoGenerateStatusRoute,
  ApiWithdrawalHistoryRoute: ApiWithdrawalHistoryRoute,
  ApiWithdrawalRequestRoute: ApiWithdrawalRequestRoute,
  V1BlocksUserIdRoute: V1BlocksUserIdRoute,
  V1ContactsUserIdRoute: V1ContactsUserIdRoute,
  V1InternalSpaceAgentBillingRoute: V1InternalSpaceAgentBillingRoute,
  V1RoomsMetadataRoute: V1RoomsMetadataRoute,
  V1SessionBootstrapRoute: V1SessionBootstrapRoute,
  V1UsersSearchRoute: V1UsersSearchRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
  ApiVideoGenerateIndexRoute: ApiVideoGenerateIndexRoute,
  V1BlocksIndexRoute: V1BlocksIndexRoute,
  V1ContactsIndexRoute: V1ContactsIndexRoute,
  V1FriendRequestsIndexRoute: V1FriendRequestsIndexRoute,
  V1RoomsIndexRoute: V1RoomsIndexRoute,
  V1SpacesIndexRoute: V1SpacesIndexRoute,
  ApiAdminBlogIdRoute: ApiAdminBlogIdRoute,
  ApiAdminPricingPlansImportRoute: ApiAdminPricingPlansImportRoute,
  ApiAdminPricingPlansReorderRoute: ApiAdminPricingPlansReorderRoute,
  ApiAdminStatsMonthlyRoute: ApiAdminStatsMonthlyRoute,
  ApiAdminWithdrawalsIdRoute: ApiAdminWithdrawalsIdRoute,
  ApiPaymentReturnPaypalRoute: ApiPaymentReturnPaypalRoute,
  ApiPaymentVerifyCreemRoute: ApiPaymentVerifyCreemRoute,
  ApiPaymentVerifyStripeRoute: ApiPaymentVerifyStripeRoute,
  ApiPaymentWebhookAlipayRoute: ApiPaymentWebhookAlipayRoute,
  ApiPaymentWebhookCreemRoute: ApiPaymentWebhookCreemRoute,
  ApiPaymentWebhookDodoRoute: ApiPaymentWebhookDodoRoute,
  ApiPaymentWebhookPaypalRoute: ApiPaymentWebhookPaypalRoute,
  ApiPaymentWebhookStripeRoute: ApiPaymentWebhookStripeRoute,
  ApiPaymentWebhookWechatRoute: ApiPaymentWebhookWechatRoute,
  V1FriendRequestsIdAcceptRoute: V1FriendRequestsIdAcceptRoute,
  V1FriendRequestsIdRejectRoute: V1FriendRequestsIdRejectRoute,
  V1RoomsRoomIdPreferencesRoute: V1RoomsRoomIdPreferencesRoute,
  V1SpacesSpaceIdFavoriteRoute: V1SpacesSpaceIdFavoriteRoute,
  V1SpacesInstancesRoomIdRoute: V1SpacesInstancesRoomIdRouteWithChildren,
  ApiAdminBlogIndexRoute: ApiAdminBlogIndexRoute,
  ApiAdminOrdersIndexRoute: ApiAdminOrdersIndexRoute,
  ApiAdminPricingPlansIndexRoute: ApiAdminPricingPlansIndexRoute,
  ApiAdminStatsIndexRoute: ApiAdminStatsIndexRoute,
  ApiAdminSubscriptionsIndexRoute: ApiAdminSubscriptionsIndexRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
  ApiAdminWithdrawalsIndexRoute: ApiAdminWithdrawalsIndexRoute,
  ApiAdminCreditsTransactionsIndexRoute: ApiAdminCreditsTransactionsIndexRoute,
  ApiAdminUsersDeleteIndexRoute: ApiAdminUsersDeleteIndexRoute,
  ApiAdminUsersUpdateIndexRoute: ApiAdminUsersUpdateIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
