/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as V1ProfileRouteImport } from './routes/v1/profile'
import { Route as V1ProductStateRouteImport } from './routes/v1/product-state'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as V1SpacesIndexRouteImport } from './routes/v1/spaces/index'
import { Route as V1RoomsIndexRouteImport } from './routes/v1/rooms/index'
import { Route as V1FriendRequestsIndexRouteImport } from './routes/v1/friend-requests/index'
import { Route as V1ContactsIndexRouteImport } from './routes/v1/contacts/index'
import { Route as V1BlocksIndexRouteImport } from './routes/v1/blocks/index'
import { Route as ApiBlogIndexRouteImport } from './routes/api/blog/index'
import { Route as V1UsersSearchRouteImport } from './routes/v1/users/search'
import { Route as V1SessionBootstrapRouteImport } from './routes/v1/session/bootstrap'
import { Route as V1RoomsMetadataRouteImport } from './routes/v1/rooms/metadata'
import { Route as V1ContactsUserIdRouteImport } from './routes/v1/contacts/$userId'
import { Route as V1BlocksUserIdRouteImport } from './routes/v1/blocks/$userId'
import { Route as ApiBlogSlugRouteImport } from './routes/api/blog/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as V1SpacesSpaceIdFavoriteRouteImport } from './routes/v1/spaces/$spaceId/favorite'
import { Route as V1RoomsRoomIdPreferencesRouteImport } from './routes/v1/rooms/$roomId/preferences'
import { Route as V1FriendRequestsIdRejectRouteImport } from './routes/v1/friend-requests/$id/reject'
import { Route as V1FriendRequestsIdAcceptRouteImport } from './routes/v1/friend-requests/$id/accept'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProfileRoute = V1ProfileRouteImport.update({
  id: '/v1/profile',
  path: '/v1/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ProductStateRoute = V1ProductStateRouteImport.update({
  id: '/v1/product-state',
  path: '/v1/product-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SpacesIndexRoute = V1SpacesIndexRouteImport.update({
  id: '/v1/spaces/',
  path: '/v1/spaces/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RoomsIndexRoute = V1RoomsIndexRouteImport.update({
  id: '/v1/rooms/',
  path: '/v1/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1FriendRequestsIndexRoute = V1FriendRequestsIndexRouteImport.update({
  id: '/v1/friend-requests/',
  path: '/v1/friend-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ContactsIndexRoute = V1ContactsIndexRouteImport.update({
  id: '/v1/contacts/',
  path: '/v1/contacts/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1BlocksIndexRoute = V1BlocksIndexRouteImport.update({
  id: '/v1/blocks/',
  path: '/v1/blocks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogIndexRoute = ApiBlogIndexRouteImport.update({
  id: '/api/blog/',
  path: '/api/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const V1UsersSearchRoute = V1UsersSearchRouteImport.update({
  id: '/v1/users/search',
  path: '/v1/users/search',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SessionBootstrapRoute = V1SessionBootstrapRouteImport.update({
  id: '/v1/session/bootstrap',
  path: '/v1/session/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RoomsMetadataRoute = V1RoomsMetadataRouteImport.update({
  id: '/v1/rooms/metadata',
  path: '/v1/rooms/metadata',
  getParentRoute: () => rootRouteImport,
} as any)
const V1ContactsUserIdRoute = V1ContactsUserIdRouteImport.update({
  id: '/v1/contacts/$userId',
  path: '/v1/contacts/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const V1BlocksUserIdRoute = V1BlocksUserIdRouteImport.update({
  id: '/v1/blocks/$userId',
  path: '/v1/blocks/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogSlugRoute = ApiBlogSlugRouteImport.update({
  id: '/api/blog/$slug',
  path: '/api/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const V1SpacesSpaceIdFavoriteRoute = V1SpacesSpaceIdFavoriteRouteImport.update({
  id: '/v1/spaces/$spaceId/favorite',
  path: '/v1/spaces/$spaceId/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const V1RoomsRoomIdPreferencesRoute =
  V1RoomsRoomIdPreferencesRouteImport.update({
    id: '/v1/rooms/$roomId/preferences',
    path: '/v1/rooms/$roomId/preferences',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1FriendRequestsIdRejectRoute =
  V1FriendRequestsIdRejectRouteImport.update({
    id: '/v1/friend-requests/$id/reject',
    path: '/v1/friend-requests/$id/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const V1FriendRequestsIdAcceptRoute =
  V1FriendRequestsIdAcceptRouteImport.update({
    id: '/v1/friend-requests/$id/accept',
    path: '/v1/friend-requests/$id/accept',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/v1/product-state': typeof V1ProductStateRoute
  '/v1/profile': typeof V1ProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/v1/blocks/$userId': typeof V1BlocksUserIdRoute
  '/v1/contacts/$userId': typeof V1ContactsUserIdRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/session/bootstrap': typeof V1SessionBootstrapRoute
  '/v1/users/search': typeof V1UsersSearchRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/v1/blocks/': typeof V1BlocksIndexRoute
  '/v1/contacts/': typeof V1ContactsIndexRoute
  '/v1/friend-requests/': typeof V1FriendRequestsIndexRoute
  '/v1/rooms/': typeof V1RoomsIndexRoute
  '/v1/spaces/': typeof V1SpacesIndexRoute
  '/v1/friend-requests/$id/accept': typeof V1FriendRequestsIdAcceptRoute
  '/v1/friend-requests/$id/reject': typeof V1FriendRequestsIdRejectRoute
  '/v1/rooms/$roomId/preferences': typeof V1RoomsRoomIdPreferencesRoute
  '/v1/spaces/$spaceId/favorite': typeof V1SpacesSpaceIdFavoriteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/v1/product-state': typeof V1ProductStateRoute
  '/v1/profile': typeof V1ProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/v1/blocks/$userId': typeof V1BlocksUserIdRoute
  '/v1/contacts/$userId': typeof V1ContactsUserIdRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/session/bootstrap': typeof V1SessionBootstrapRoute
  '/v1/users/search': typeof V1UsersSearchRoute
  '/api/blog': typeof ApiBlogIndexRoute
  '/v1/blocks': typeof V1BlocksIndexRoute
  '/v1/contacts': typeof V1ContactsIndexRoute
  '/v1/friend-requests': typeof V1FriendRequestsIndexRoute
  '/v1/rooms': typeof V1RoomsIndexRoute
  '/v1/spaces': typeof V1SpacesIndexRoute
  '/v1/friend-requests/$id/accept': typeof V1FriendRequestsIdAcceptRoute
  '/v1/friend-requests/$id/reject': typeof V1FriendRequestsIdRejectRoute
  '/v1/rooms/$roomId/preferences': typeof V1RoomsRoomIdPreferencesRoute
  '/v1/spaces/$spaceId/favorite': typeof V1SpacesSpaceIdFavoriteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/upload': typeof ApiUploadRoute
  '/v1/product-state': typeof V1ProductStateRoute
  '/v1/profile': typeof V1ProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/blog/$slug': typeof ApiBlogSlugRoute
  '/v1/blocks/$userId': typeof V1BlocksUserIdRoute
  '/v1/contacts/$userId': typeof V1ContactsUserIdRoute
  '/v1/rooms/metadata': typeof V1RoomsMetadataRoute
  '/v1/session/bootstrap': typeof V1SessionBootstrapRoute
  '/v1/users/search': typeof V1UsersSearchRoute
  '/api/blog/': typeof ApiBlogIndexRoute
  '/v1/blocks/': typeof V1BlocksIndexRoute
  '/v1/contacts/': typeof V1ContactsIndexRoute
  '/v1/friend-requests/': typeof V1FriendRequestsIndexRoute
  '/v1/rooms/': typeof V1RoomsIndexRoute
  '/v1/spaces/': typeof V1SpacesIndexRoute
  '/v1/friend-requests/$id/accept': typeof V1FriendRequestsIdAcceptRoute
  '/v1/friend-requests/$id/reject': typeof V1FriendRequestsIdRejectRoute
  '/v1/rooms/$roomId/preferences': typeof V1RoomsRoomIdPreferencesRoute
  '/v1/spaces/$spaceId/favorite': typeof V1SpacesSpaceIdFavoriteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/api/upload'
    | '/v1/product-state'
    | '/v1/profile'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/v1/blocks/$userId'
    | '/v1/contacts/$userId'
    | '/v1/rooms/metadata'
    | '/v1/session/bootstrap'
    | '/v1/users/search'
    | '/api/blog/'
    | '/v1/blocks/'
    | '/v1/contacts/'
    | '/v1/friend-requests/'
    | '/v1/rooms/'
    | '/v1/spaces/'
    | '/v1/friend-requests/$id/accept'
    | '/v1/friend-requests/$id/reject'
    | '/v1/rooms/$roomId/preferences'
    | '/v1/spaces/$spaceId/favorite'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/api/upload'
    | '/v1/product-state'
    | '/v1/profile'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/v1/blocks/$userId'
    | '/v1/contacts/$userId'
    | '/v1/rooms/metadata'
    | '/v1/session/bootstrap'
    | '/v1/users/search'
    | '/api/blog'
    | '/v1/blocks'
    | '/v1/contacts'
    | '/v1/friend-requests'
    | '/v1/rooms'
    | '/v1/spaces'
    | '/v1/friend-requests/$id/accept'
    | '/v1/friend-requests/$id/reject'
    | '/v1/rooms/$roomId/preferences'
    | '/v1/spaces/$spaceId/favorite'
  id:
    | '__root__'
    | '/'
    | '/api/health'
    | '/api/upload'
    | '/v1/product-state'
    | '/v1/profile'
    | '/api/auth/$'
    | '/api/blog/$slug'
    | '/v1/blocks/$userId'
    | '/v1/contacts/$userId'
    | '/v1/rooms/metadata'
    | '/v1/session/bootstrap'
    | '/v1/users/search'
    | '/api/blog/'
    | '/v1/blocks/'
    | '/v1/contacts/'
    | '/v1/friend-requests/'
    | '/v1/rooms/'
    | '/v1/spaces/'
    | '/v1/friend-requests/$id/accept'
    | '/v1/friend-requests/$id/reject'
    | '/v1/rooms/$roomId/preferences'
    | '/v1/spaces/$spaceId/favorite'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiUploadRoute: typeof ApiUploadRoute
  V1ProductStateRoute: typeof V1ProductStateRoute
  V1ProfileRoute: typeof V1ProfileRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBlogSlugRoute: typeof ApiBlogSlugRoute
  V1BlocksUserIdRoute: typeof V1BlocksUserIdRoute
  V1ContactsUserIdRoute: typeof V1ContactsUserIdRoute
  V1RoomsMetadataRoute: typeof V1RoomsMetadataRoute
  V1SessionBootstrapRoute: typeof V1SessionBootstrapRoute
  V1UsersSearchRoute: typeof V1UsersSearchRoute
  ApiBlogIndexRoute: typeof ApiBlogIndexRoute
  V1BlocksIndexRoute: typeof V1BlocksIndexRoute
  V1ContactsIndexRoute: typeof V1ContactsIndexRoute
  V1FriendRequestsIndexRoute: typeof V1FriendRequestsIndexRoute
  V1RoomsIndexRoute: typeof V1RoomsIndexRoute
  V1SpacesIndexRoute: typeof V1SpacesIndexRoute
  V1FriendRequestsIdAcceptRoute: typeof V1FriendRequestsIdAcceptRoute
  V1FriendRequestsIdRejectRoute: typeof V1FriendRequestsIdRejectRoute
  V1RoomsRoomIdPreferencesRoute: typeof V1RoomsRoomIdPreferencesRoute
  V1SpacesSpaceIdFavoriteRoute: typeof V1SpacesSpaceIdFavoriteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/profile': {
      id: '/v1/profile'
      path: '/v1/profile'
      fullPath: '/v1/profile'
      preLoaderRoute: typeof V1ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/product-state': {
      id: '/v1/product-state'
      path: '/v1/product-state'
      fullPath: '/v1/product-state'
      preLoaderRoute: typeof V1ProductStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/spaces/': {
      id: '/v1/spaces/'
      path: '/v1/spaces'
      fullPath: '/v1/spaces/'
      preLoaderRoute: typeof V1SpacesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/rooms/': {
      id: '/v1/rooms/'
      path: '/v1/rooms'
      fullPath: '/v1/rooms/'
      preLoaderRoute: typeof V1RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/friend-requests/': {
      id: '/v1/friend-requests/'
      path: '/v1/friend-requests'
      fullPath: '/v1/friend-requests/'
      preLoaderRoute: typeof V1FriendRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/contacts/': {
      id: '/v1/contacts/'
      path: '/v1/contacts'
      fullPath: '/v1/contacts/'
      preLoaderRoute: typeof V1ContactsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/blocks/': {
      id: '/v1/blocks/'
      path: '/v1/blocks'
      fullPath: '/v1/blocks/'
      preLoaderRoute: typeof V1BlocksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/': {
      id: '/api/blog/'
      path: '/api/blog'
      fullPath: '/api/blog/'
      preLoaderRoute: typeof ApiBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/users/search': {
      id: '/v1/users/search'
      path: '/v1/users/search'
      fullPath: '/v1/users/search'
      preLoaderRoute: typeof V1UsersSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/session/bootstrap': {
      id: '/v1/session/bootstrap'
      path: '/v1/session/bootstrap'
      fullPath: '/v1/session/bootstrap'
      preLoaderRoute: typeof V1SessionBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/rooms/metadata': {
      id: '/v1/rooms/metadata'
      path: '/v1/rooms/metadata'
      fullPath: '/v1/rooms/metadata'
      preLoaderRoute: typeof V1RoomsMetadataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/contacts/$userId': {
      id: '/v1/contacts/$userId'
      path: '/v1/contacts/$userId'
      fullPath: '/v1/contacts/$userId'
      preLoaderRoute: typeof V1ContactsUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/blocks/$userId': {
      id: '/v1/blocks/$userId'
      path: '/v1/blocks/$userId'
      fullPath: '/v1/blocks/$userId'
      preLoaderRoute: typeof V1BlocksUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog/$slug': {
      id: '/api/blog/$slug'
      path: '/api/blog/$slug'
      fullPath: '/api/blog/$slug'
      preLoaderRoute: typeof ApiBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/spaces/$spaceId/favorite': {
      id: '/v1/spaces/$spaceId/favorite'
      path: '/v1/spaces/$spaceId/favorite'
      fullPath: '/v1/spaces/$spaceId/favorite'
      preLoaderRoute: typeof V1SpacesSpaceIdFavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/rooms/$roomId/preferences': {
      id: '/v1/rooms/$roomId/preferences'
      path: '/v1/rooms/$roomId/preferences'
      fullPath: '/v1/rooms/$roomId/preferences'
      preLoaderRoute: typeof V1RoomsRoomIdPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/friend-requests/$id/reject': {
      id: '/v1/friend-requests/$id/reject'
      path: '/v1/friend-requests/$id/reject'
      fullPath: '/v1/friend-requests/$id/reject'
      preLoaderRoute: typeof V1FriendRequestsIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v1/friend-requests/$id/accept': {
      id: '/v1/friend-requests/$id/accept'
      path: '/v1/friend-requests/$id/accept'
      fullPath: '/v1/friend-requests/$id/accept'
      preLoaderRoute: typeof V1FriendRequestsIdAcceptRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiUploadRoute: ApiUploadRoute,
  V1ProductStateRoute: V1ProductStateRoute,
  V1ProfileRoute: V1ProfileRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBlogSlugRoute: ApiBlogSlugRoute,
  V1BlocksUserIdRoute: V1BlocksUserIdRoute,
  V1ContactsUserIdRoute: V1ContactsUserIdRoute,
  V1RoomsMetadataRoute: V1RoomsMetadataRoute,
  V1SessionBootstrapRoute: V1SessionBootstrapRoute,
  V1UsersSearchRoute: V1UsersSearchRoute,
  ApiBlogIndexRoute: ApiBlogIndexRoute,
  V1BlocksIndexRoute: V1BlocksIndexRoute,
  V1ContactsIndexRoute: V1ContactsIndexRoute,
  V1FriendRequestsIndexRoute: V1FriendRequestsIndexRoute,
  V1RoomsIndexRoute: V1RoomsIndexRoute,
  V1SpacesIndexRoute: V1SpacesIndexRoute,
  V1FriendRequestsIdAcceptRoute: V1FriendRequestsIdAcceptRoute,
  V1FriendRequestsIdRejectRoute: V1FriendRequestsIdRejectRoute,
  V1RoomsRoomIdPreferencesRoute: V1RoomsRoomIdPreferencesRoute,
  V1SpacesSpaceIdFavoriteRoute: V1SpacesSpaceIdFavoriteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
