/**
 * Build-time script: compiles MJML templates to static HTML and writes
 * them as a TypeScript module (compiled.ts).
 *
 * Run via `pnpm email:compile` from the repo root.
 *
 * After compilation, the runtime email module only needs Handlebars
 * for variable substitution — mjml and its heavy CJS dependency tree
 * (html-minifier, uglify-js, clean-css) are never loaded at runtime,
 * making the email lib fully compatible with Cloudflare Workers / edge runtimes.
 */
import mjml2html from 'mjml';
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { VERIFICATION_TEMPLATE, RESET_PASSWORD_TEMPLATE } from './templates';

const __dirname = dirname(fileURLToPath(import.meta.url));

const entries: { exportName: string; mjml: string }[] = [
  { exportName: 'VERIFICATION_HTML', mjml: VERIFICATION_TEMPLATE },
  { exportName: 'RESET_PASSWORD_HTML', mjml: RESET_PASSWORD_TEMPLATE },
];

const lines: string[] = [
  '// AUTO-GENERATED by libs/email/templates/compile.ts — DO NOT EDIT',
  '// Re-generate with: pnpm email:compile',
  '',
];

for (const { exportName, mjml } of entries) {
  const { html, errors } = mjml2html(mjml);
  if (errors.length) {
    console.error(`MJML errors in ${exportName}:`, errors);
    process.exit(1);
  }
  const escaped = html.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');
  lines.push(`export const ${exportName} = \`${escaped}\`;`);
  lines.push('');
  console.log(`✅ compiled ${exportName}`);
}

const outPath = join(__dirname, 'compiled.ts');
writeFileSync(outPath, lines.join('\n'), 'utf-8');
console.log(`\nWrote ${outPath}`);
